### ISSUE TITLE
Please use annotated tags for releases

### ISSUE THREAD

**Issue by nesciens** [davidgfnet/whatsapp-purple#101]
Running git describe on current master yields v0.3-41-g1f8df34 (meaning tag v0.3, plus 41 commits, head g1f8df34) instead of the desired v0.4-2-2-g1f8df34 (meaning tag v0.4-2, plus 2 commits, head g1f8df34). Not a big issue, since the right description can be retrieved with git describe --tags, but slightly annoying.

From man git-tag:
Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels. For this reason, some git commands for naming objects (like git describe) will ignore lightweight tags by default.

**Comment by davidgfnet** [comment]
Let me close this. I think I won't use annotated tags. We don't tag much things actually. Thanks for the help!
