### ISSUE TITLE
No Profile Image or Status Message

### ISSUE THREAD

**Issue by erbn** [davidgfnet/whatsapp-purple#105]
On Ubuntu 13.10 I've installed Pidgin and your plugin for WhatsApp.

I'm very happy about this feature, I can send and recieve messages or can even use groups.

Alas it is not possible neither to add a profile image nor a status message, although I can select a picture and a status in the bottom edge of pidgin.

**Comment by ducklin5** [comment]
Have there been any updates to fix this yet? Please confirm if so :smile:

**Comment by erbn** [comment]
No, at least as far as I know.

**Comment by shirishag75** [comment]
hi all, 
this is still a bug. I git pulled the latest version 0.7 from git, compiled it and added it pidgin 2.10.11 on Debian testing/soon to be stable. 

I am able to see profile pictures of people at 96x96 so scaled down my picture to that resolution and while it saved, people are not able to see it as of now.

**Comment by davidgfnet** [comment]
Thanks for the headsup shirish, notice my irony here...

**Comment by mlopezgva** [comment]
David no plans to fix at least the avatar image?
My wife is still kidding me because I've no profile pic... :D :D

Thx

2015-01-30 13:05 GMT-02:00 David G. F. <notifications@github.com>:

> Thanks for the headsup shirish, notice my irony here...
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/davidgfnet/whatsapp-purple/issues/105#issuecomment-72214259>
> .
>



-- 
Atte.,

*Manuel López*

**Comment by shirishag75** [comment]
Umm... just sharing with all, apparently a bit of improvement has come, will compile and then see if that part has been taken care of :-

    commit 3778596585a30507b0cc8fa439176e9922e0a658
    Author: David Guillen Fandos <david@davidgf.net>
    Date:   Wed Feb 25 18:27:01 2015 +0000
    
        Fixed status message update.
        This fixes partially issue no. 105.
    
Will be able to comment in the same comment if it works or not after compiling it and adding it to the pidgin if the situation improves.

**Comment by davidgfnet** [comment]
Pretty easy dude:
http://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Gaim-buddylist-2.0.0b6.png/220px-Gaim-buddylist-2.0.0b6.png

**Comment by salvattore001** [comment]
my profile picture it's ok but the status it's not working for me. my contacts see "hey there i'm using whatsapp"
am i missing something?

**Comment by davidgfnet** [comment]
This changes are not included in v0.7. I will include them in the new version v0.8 to come probably next week.

**Comment by salvattore001** [comment]
great!

On 26 February 2015 at 20:45, David G. F. <notifications@github.com> wrote:

> This changes are not included in v0.7. I will include them in the new
> version v0.8 to come probably next week.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidgfnet/whatsapp-purple/issues/105#issuecomment-76300481>
> .
>



-- 
============================//
Martin Salvador Greco
http://www.facebook.com/salvattore001
http://www.flickr.com/photos/salvattore001

**Comment by shirishag75** [comment]
ah, I was getting the same messages , thought probably I was mis-reading it. 

![whatsapp-status-issue-2](https://cloud.githubusercontent.com/assets/727626/6494344/fdf99902-c2e6-11e4-93b8-33bdff974f64.png)

I have put the status as, "Trying out the status thingie" , look forward to seeing the update.

**Comment by davidgfnet** [comment]
Works for me... Are you sure you're running latest version? And by latest version I always mean master/HEAD

**Comment by shirishag75** [comment]
I *think* I am running the master/HEAD . This is the command I always use while doing the update :-

    ~/games/whatsapp-purple$ git pull origin master
    From https://github.com/davidgfnet/whatsapp-purple
     * branch            master     -> FETCH_HEAD
    Already up-to-date.
    
Then this is what I follow each time when I make the .deb file. I first remove the old one (as it doesn't have any account info., logs or anything should be safe)

    $ sudo dpkg -P pidgin-whatsapp
    [sudo] password for shirish: 
    D000001: ensure_diversions: new, (re)loading
    D000001: process queue pkg pidgin-whatsapp:amd64 queue.len 0 progress 1, try 1
    D000001: deferred_remove package pidgin-whatsapp:amd64
    D000001: checking dependencies for remove 'pidgin-whatsapp:amd64'
    (Reading database ... 623614 files and directories currently installed.)
    Removing pidgin-whatsapp (0.7) ...
    D000001: removal_bulk package pidgin-whatsapp:amd64
    D000001: removal_bulk cleaning info directory
    D000001: removal_bulk purging? foundpostrm=0
    D000001: removal_bulk no postrm, no conffiles, purging
    D000001: removal_bulk purge done, removing list '/var/lib/dpkg/info/pidgin-whatsapp.list'
    D000001: removal_bulk purge done, removing postrm '/var/lib/dpkg/info/pidgin-whatsapp.postrm'
    D000001: removal done
    D000001: cmpversions a='0:1.17.24' b='0:1.16' r=1
    D000001: cmpversions a='0:1.17.24' b='0:1.16' r=1
    
Sorry for the extended output, I have made the installation verbose so I can check or know if something is going wrong somewhere. 

and then install in the new version of the update. 

    ~/games$ sudo dpkg -i pidgin-whatsapp_0.7_amd64.deb 
    [sudo] password for shirish: 
    D000001: ensure_diversions: new, (re)loading
    D000001: ensure_statoverrides: new, (re)loading
    Selecting previously unselected package pidgin-whatsapp.
    (Reading database ... 623607 files and directories currently installed.)
    Preparing to unpack pidgin-whatsapp_0.7_amd64.deb ...
    D000001: process_archive oldversionstatus=not installed
    Unpacking pidgin-whatsapp (0.7) ...
    D000001: process_archive updating info directory
    D000001: generating infodb hashfile
    D000001: process queue pkg pidgin-whatsapp:amd64 queue.len 0 progress 1, try 1
    Setting up pidgin-whatsapp (0.7) ...
    D000001: deferred_configure updating conffiles
    D000001: cmpversions a='0:1.17.24' b='0:1.16' r=1
    D000001: cmpversions a='0:1.17.24' b='0:1.16' r=1
    
Please let me know if I'm doing anything wrong.

**Comment by dequis** [comment]
Good way to ensure you're using latest master: it should crash when you receive messages. See #231

**Comment by shirishag75** [comment]
umm... confused. The latest as I can see in git log is :-

    ~/games/whatsapp-purple$ git log | less
    commit e9303f476469a6c74c5aec62cfdc87c1c1bb9082
    Author: David Guillen Fandos <david@davidgf.net>
    Date:   Mon Mar 2 19:40:51 2015 +0000
    
        Fix some leaks. Thanks to dx!

And this corresponds with what is shared on https://github.com/davidgfnet/whatsapp-purple/tree/master as the same message is displayed. 

I also used git branch to see if I'm not on master and it shows I'm not. 

    ~/games/whatsapp-purple$ git branch
    * master

Stumped here.

**Comment by davidgfnet** [comment]
Fixed!
