### ISSUE TITLE
Auto crash after one minute

### ISSUE THREAD

**Issue by bingAring** [davidgfnet/whatsapp-purple#125]
i am having this issue. i set up my whatsapp account with help of whatsapp-purple. i can send and recieve messages also. however, this only happens with whatsapp account that pidgin automatically closes after one minute, even when i am active and typing something, it closes itself. it is very annoying. Is it just me or others are also facing this issue?
please show me some solution.
i am running pidgin, having linux OS: elementary Luna(Ubuntu 12.04)

**Comment by davidgfnet** [comment]
Closing this... Too old
