### ISSUE TITLE
i can't send image 

### ISSUE THREAD

**Issue by angelbladex** [davidgfnet/whatsapp-purple#138]
i dont can now send photos :S

a fragment of output for pidgin -d
...
(06:57:11) prpl-whatsapp: File xfer init...
(06:57:11) prpl-whatsapp: Transfer file a.png at /home/angelblade/Desktop/a.png with size 50705 (given ref 110)
(06:57:11) waprpl: Establishing SSL connection to mms836.whatsapp.net:443
(06:57:11) dnsquery: Performing DNS lookup for mms836.whatsapp.net
(06:57:11) dns: Wait for DNS child 2349 failed: No hay ningún proceso hijo
(06:57:11) dns: Created new DNS child 2365, there are now 1 children.
(06:57:11) dns: Successfully sent DNS request to child 2365
(06:57:11) dns: Got response for 'mms836.whatsapp.net'
(06:57:11) dnsquery: IP resolved for mms836.whatsapp.net
(06:57:11) proxy: Attempting connection to 184.173.136.68
(06:57:11) proxy: Connecting to mms836.whatsapp.net:443 with no proxy
(06:57:11) proxy: Connection in progress
(06:57:27) proxy: Connecting to mms836.whatsapp.net:443.
(06:57:27) proxy: Error connecting to mms836.whatsapp.net:443 (No existe ninguna ruta hasta el `host').
(06:57:27) proxy: Connection attempt failed: No existe ninguna ruta hasta el `host'
dns[2365]: nobody needs me... =(
....

I got message new version of whatsapp 2-4 weeks before.

**Comment by shirishag75** [comment]
umm.... am I reading it right, can't send pictures to groups at moment, right ? If that is true, it should be in the errata somewhere so people know and don't bother you @davidgfnet

**Comment by davidgfnet** [comment]
Stupid people will always bother me or somebody else, no matter how much we
document things...

Do you realise that every time someone updates an issue I get an email
right?
Please be concious about that...
