### ISSUE TITLE
request  for source code for Xabber whatsapp 

### ISSUE THREAD

**Issue by laddhika** [davidgfnet/whatsapp-purple#147]
@davidgfnet I am looking for a source code compatible with Xabber watsapp which is compiled by you, the current source code you have posted in GitHub has an error with its WAConnection, Therefore please be kind enough to send me a fully working source code that I can work with watsapp using Xabber to my email.

My email address is below for your kind reference
softwarehelp12123@gmail.com

**Comment by fionnlagh** [comment]
You could use a private jabber server with Spectrum2. Spectrum2 supports purple plugins and I once tested this whatsapp-purple plugin with my server. The only thing is: if you do it this way, it does not support group chats (or it at least did not for me)

**Comment by annonbacca** [comment]
@fionnlagh Hey do you happen to know alternatives that could be used on Android, the Spectrum2 can't run on android off the shelf, and I am interested in a Xabber like client for whatsapp that could be used on Android.

**Comment by davidgfnet** [comment]
Fixing spectrum2 interwork its probably worth the time. I mean, mantaining Xabber support its boring and it make you stick to that particular client.
Id like to use Conversations for instance. Way better client.

**Comment by davidgfnet** [comment]
BTW I'll close this, since it is something more xabber related.
