### ISSUE TITLE
Lately keeps disconnecting and reconnecting, cannot send/receive messages

### ISSUE THREAD

**Issue by GitAnt** [davidgfnet/whatsapp-purple#151]
I'm using the plugin with pidgin and lately it's started disconnecting after a minute from the connection and the contacts appear in the list but they don't receive my messages and I can't receive theirs. For every contact I get

Status: Unavailable
Last seen on WhatsApp: 0 seconds
Status Message:

I tried to start the program in the command line but it's not very helpful, all I get is

(10:02:59) dnsquery: Performing DNS lookup for c3.whatsapp.net
(10:02:59) dns: Got response for 'c3.whatsapp.net'
(10:02:59) dnsquery: IP resolved for c3.whatsapp.net
(10:02:59) proxy: Connecting to c3.whatsapp.net:443 with no proxy
(10:02:59) proxy: Connecting to c3.whatsapp.net:443.
(10:02:59) proxy: Connected to c3.whatsapp.net:443.
(10:02:59) blist: Updating buddy status for ############ (WhatsApp)
...

and so on for all the contacts. I'm using the latest code from the repo and 
Pidgin 2.10.9 (libpurple 2.10.9) on Ubuntu 14.04

**Comment by davidgfnet** [comment]
Closing this. If you have more problems open a new issue.
As always try to be as detailed as possible and ALWAYS use the latest version, otherwise it's very difficult to debug.
