### ISSUE TITLE
Whatsapp changes makes this plugin useless now

### ISSUE THREAD

**Issue by Jemshi101** [davidgfnet/whatsapp-purple#162]
New changes made mandatory by whatsapp lately has made this plugin useless now.
The changes made by whatsapp is causing the plugin not to send a successfull message and does not show any group members in the list of group members.
so can you fix it asap.
I just dont want your efforts to become worthless anymore.
Thanks

**Comment by dequis** [comment]
Can this ticket be closed or at least change the title to something less misleading? It's been bothering me, every time I look at this tracker.

**Comment by Jemshi101** [comment]
Can Anyone provide me with the latest Whatsapp.dll compiled from the repository so that i can test it and mark everything closed. I Lack the knowledge to do so myself. Thanks for everything.

**Comment by Cybernetic1** [comment]
Starting about 3rd March 2015, I get "server closed connection" error.
Pidgin = 2.10.9 (libPurple 2.10.9)
I was using:
server = c2.whatsapp.net
resource = WP7-2.11.596-443
but suddenly it ceased to work.  Anyone have similar issue?

**Comment by davidgfnet** [comment]
See #224
