### ISSUE TITLE
Can you add the message sent and delivered notifications?

### ISSUE THREAD

**Issue by pteek** [davidgfnet/whatsapp-purple#169]
The two ticks.

Also, history is deleted as soon as the chat windows is closed.

**Comment by davidgfnet** [comment]
This is done! In a separate repo, since it is Pidgin specific (do not confuse pidgin with libpurple although they are kind of the same).
Commit 6c2e8bdeb6f46e77a4e782522fa8e1ae4914905b enables the mentioned plugin by emitting the appropriate signals.
