### ISSUE TITLE
c3.whatsapp.net not working

### ISSUE THREAD

**Issue by mkolchin** [davidgfnet/whatsapp-purple#171]
Server closed the connection

**Comment by tijelino** [comment]
Server: S 40-2.12.11-443  (with the space between the S and the 4)

worked for me in spain

**Comment by SergeyDjam** [comment]
work now. Russia

**Comment by mkolchin** [comment]
How do you get it?

**Comment by mkolchin** [comment]
connection: Connection error on 0x85834c8 (reason: 2 description: not-authorized)

**Comment by davidgfnet** [comment]
Not authorized means wrong user and/or password... Sometimes could mean
banned as well

**Comment by mkolchin** [comment]
https://github.com/shirioko/WART
Where to get WART?

**Comment by davidgfnet** [comment]
https://github.com/mgp25/WART

**Comment by mkolchin** [comment]
Thanks it worked!

**Comment by yatahid** [comment]
WhatsApp on Pidgin can't connect
Server closed the connection

**Comment by yatahid** [comment]
WhatsApp on Pidgin can't connect
Server closed the connection
Resource: Android-2.31.151-443

**Comment by erwin68** [comment]
My system ubuntu 12.04
Did WA-Registration with yowsup.
Then installed pidgin and whatsapp-purple.
Then it worked fine for one evening.

Next day at starting up pidgin I got "not-authorized".
But logon with yowsup worked fine.
Then I only changed Resource to Android-2.31.151-443 an pidgin worked again.

Seems that "not-authorized" indicated not that my number was blocked or that the number/password was wrong but "client is not accepted"

**Comment by KottV** [comment]
I just found, that c1 c2 c3 whatsapp.net became unreachable, so I searched for their servers addresses, and typed first random 184.173.136.66
now it connects, so far

**Comment by davidgfnet** [comment]
@KottV C* servers are no longer used. Look at the source. Use E instead. Leaving the box empty will use a random server.

**Comment by KottV** [comment]
oh, news
excuse me, what is "E" ? :)
and I tried with empty "server" fields now, unsuccesfull

**Comment by davidgfnet** [comment]
e1.whatsapp.net, e2.whatsapp.net ...

**Comment by KottV** [comment]
understand, thnx

**Comment by frenton** [comment]
I switched server to 

e1.whatsapp.net:443

but still getting exception

"Fatal error: Uncaught exception 'Exception' with message 'Login Failure' in ..." 

even though the number is not blocked. I checked it using WART repeatedly. Does anybody know, what might be the problem?

**Comment by angelbladex** [comment]
Ahhh i was having problems for use the plugin, i change versión to Android-2.31.151-443 and solved. I was thinking my account was blocked but i changed my password vía yowsup and my account was OK

**Comment by davidgfnet** [comment]
Are you guys having problems with message reception using Android as
resource? Some people do complain that login in as Android forces end to
end encryption.

**Comment by r-ace** [comment]
? Reactivate it using S40? (Small how-to, please?) OS btw: Ubuntu 15.04.

**Comment by r-ace** [comment]
Or do you mean: S 40-2.12.11-443 in Account setting -> Advanced -> Resource?

**Comment by r-ace** [comment]
Unfortunately, tried several advanced account configs, no solution so far.

**Comment by qohelet** [comment]
I started to use WhatsApp via Pidgin yesterday (installed via apt-get). I could send messages but was never able to receive anything. I am located in Uzbekistan and tried the app before on a Nokia 301.1 then on a Wexler.Tab 7iD with Android 4.1.1 - both worked fine.

My settings:
Server: e1.whatsapp.net
Resource: Android-2.31.151-443

Before I tried the old Server c2.whatsapp.net - no changes.
Strangely I can see my friends typing. Yet no message ever reached me - but everything which was sent to me is shown as read. 

I'm carefully trying now something else: 
Resource: Android-4.1.1
Nickname: Qohelet

No changes - yet strange. Apparently it's not so important what's standing there. I assume it might be just needed to change it once to acknowledge WhatsApp "something" happened.

Ideas?

**Comment by legolasbdn** [comment]
Hi there,

I have the same issue than qohelet, i'm from spain if that helps.

Thank you.

**Comment by vinipsmaker** [comment]
I cannot connect anymore. I've tried lots of approaches. I'm from Brazil, if that helps. -.-"

**Comment by KottV** [comment]
I've got some trouble yesterday. Then I updated yowsup from git, run ./yowsup-cli registration -p <nomber> -C <code> -r sms

now it works

**Comment by vinipsmaker** [comment]
> Then I updated yowsup from git, run ./yowsup-cli registration -p "number" -C "code" -r sms

> now it works

It worked here too.
