### ISSUE TITLE
Not receiving messages - Only sending

### ISSUE THREAD

**Issue by victorjabur** [davidgfnet/whatsapp-purple#179]
I'm not receiving messages. Only sending.
The status is showed: "people is typing a message ..." But the message never comes ...

**Comment by chetanunadkat90** [comment]
thanks axel21a

**Comment by chopra-anuj** [comment]
Same problem with whatsapp in my my android phone. How to solve?

**Comment by davidgfnet** [comment]
I'm working on it :P

**Comment by chopra-anuj** [comment]
Solved by itself. Now it is working fine.

**Comment by ShreyashPromact** [comment]
I have Nokia C7. I am facing same issue. I can able to send messages. I have checked that my friend is getting messages. But I am not able to get the confirmation that My friend got messages and I am also not able to get any messages from any other person.

What i need to do to resolved it.

Sincerely,
Shreyash
