### ISSUE TITLE
Setting not saved

### ISSUE THREAD

**Issue by chtenb** [davidgfnet/whatsapp-purple#188]
Each time I run pidgin, I cannot connect to whatsapp, unless I manually go to `edit account -> advanced` and empty the `resource` field.
By default this resource field says `Android-2.11.151-443` for me, but I want it to be empty obviously, since only that seems to work.

It should not reset each time I run pidgin, but remember my setting.

**Comment by Chiel92** [comment]
Well yeah, filling in `Android-3` in the field simply works.
