### ISSUE TITLE
Messages sent but not delivered (solved)

### ISSUE THREAD

**Issue by Chrunchbang** [davidgfnet/whatsapp-purple#195]
The messages that I sent to my friends seem that are sent, but my friends doesn't receive. What does it matter? Someone receive, others don't receive. I can receive messages, But I can't say tha I'm receiving all messages that my friends send to me.

**Comment by davidgfnet** [comment]
Ok great!
Definitely not. Distributing Linux binaries should always be done through repository systems, therefore no more .so files :)
