### ISSUE TITLE
Windows binaries unavailable

### ISSUE THREAD

**Issue by sbwMikael** [davidgfnet/whatsapp-purple#197]
Hi - the advertised link gives a 404 for the Windows binaries (https://davidgf.net/nightly/whatsapp-purple/404.php).

Additionally, I installed Dev-C++ to try to build from source, but the IDE gives the following messages:

  CreateProcess((null), mingw32-pkg-config --variable=plugindir purple, ...) failed. 
  CreateProcess((null), mingw32-pkg-config --variable=datarootdir purple, ...) failed. 
  CreateProcess((null), mingw32-pkg-config --cflags purple, ...) failed. 
  CreateProcess((null), i686-w64-mingw32-gcc -c -O2 -m32 -Wall -Wextra -fPIC -DPURPLE_PLUGINS -DPIC -o wa_purple.o wa_purple.c, ...) failed. 
  The system cannot find the file specified. 
 C:\Users\Username\Desktop\WA\Makefile.mingw [Build Error]  [wa_purple.o] Error 2 

...I have no experience with these compiler tools, so I don't know where to start with figuring out what's wrong.

**Comment by axel21a** [comment]
I agree that we too must learn to compilarci alone the dll, but since we do not have all the same knowledge and preparation, it would be useful for someone to tell us how to do, especially with windows.
knowledge is disclosed inthis way, do you regard to be a teacher with her students.
I personally think your great job, but I do not have your skills, then I tell you right now thanks for what you will do.

**Comment by davidgfnet** [comment]
There is no error in the log you posted. How am I supposed to guess where the problem is?

**Comment by wvxoxg** [comment]
When I tried to compile it again it showed me following

-------------- Build: Debug in Whatsapp (compiler: GNU GCC Compiler)---------------

Running command: mingw32-make.exe -f Makefile.mingw Debug
mingw32-g++ -shared -o whatsapp.dll wa_purple.o whatsapp-protocol.o wa_api.o libwhatsapp.res -LC:/CodeBlocks/MinGW/lib -lpurple -lglib-2.0 -lintl    -static-libgcc -static-libstdc++ 
mingw32-g++: error: unrecognized command line option '-static-libstdc++'
mingw32-make.exe: *** [whatsapp.dll] Error 1
Process terminated with status 2 (0 minute(s), 0 second(s))
0 error(s), 0 warning(s) (0 minute(s), 0 second(s))

**Comment by davidgfnet** [comment]
OK I see. You either need a static version of libstdc++ or just remove the "-static-libstdc++" from the Makefile. You'll need some .dlls to make it run, but should work.

**Comment by axel21a** [comment]
I state that are not practical programming.
I installed Mingw with libraries through the program mingw-get-inst-20120426.exe
gives me this compilation error.
I try to learn
I have set before the system variables?


Microsoft Windows [Versione 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tutti i diritti riservati.

C:\MinGW\bin>mingw32-make.exe -f Makefile.mingw Debug

C:\MinGW\bin>mingw32-make.exe -f d:\1d\whatsapp-purple-master\Makefile.mingw Debug
process_begin: CreateProcess(NULL, mingw32-pkg-config --variable=plugindir purple, ...) failed.
process_begin: CreateProcess(NULL, mingw32-pkg-config --variable=datarootdir purple, ...) failed.
mingw32-make.exe: *** No rule to make target `wa_purple.o', needed by `libwhatsapp.dll'.  
Stop.

C:\MinGW\bin>

**Comment by wvxoxg** [comment]
Okay, It worked. Thanks.

**Comment by micha137** [comment]
OK, the discussion for building whatsapp-purple is over.  But the initial point of this issue, "the advertised link gives a 404 for the Windows binaries (https://davidgf.net/nightly/whatsapp-purple/404.php)" is still open...

**Comment by axel21a** [comment]
#202

**Comment by rsuzano** [comment]
Hi,

The windows binaries remains unavailable... Anyone can help?

**Comment by Edszx** [comment]
Can someone please provide an updated windows binary already compiled?

**Comment by rsuzano** [comment]
@Edszx , on issue #202 @wvxoxg posted a URL to download a functional windows binary (DLL). Please check if that is enough to you. Kind Regards

**Comment by micha137** [comment]
Some more official release would be better...

**Comment by Edszx** [comment]
Thanks @rsuzano problem solved, for now at least.

**Comment by axel21a** [comment]
from what I understand, davidgfnet not release more tracks for windows

**Comment by JonnyThree** [comment]
hello i am not a programmer, i have tryed to read this topic but i don't have any idea how to obtain this dll for windows 7. can anyone help me please?

**Comment by sbwMikael** [comment]
Hi JonnyThree. axel21a posted a link to a compiled dll file here:

http://s000.tinyupload.com/index.php?file_id=01737286875689956205

I'm always uneasy about using compiled files from an untrusted source, but for the time-being I don't any other optionn

**Comment by JonnyThree** [comment]
very thanks for sharing. is really sad that David does not release more this plugin for windows. wa with pidgin is really confortable to use.

**Comment by davidgfnet** [comment]
I'm working on it. There is a new plugin to see the "ticks" and I haven't managed to compile it for windows yet. On Linux works great BTW.

**Comment by mlopezgva** [comment]
How can I get this new version?

**Comment by alikbn** [comment]
hi..  
I tried compiling it on codebloocks.. 



-------------- Build: Debug in whatsapp (compiler: GNU GCC Compiler)---------------

Running command: mingw32-make.exe -f Makefile.mingw  
process_begin: CreateProcess(NULL, mingw32-pkg-config --variable=plugindir purple, ...) failed.
process_begin: CreateProcess(NULL, mingw32-pkg-config --variable=datarootdir purple, ...) failed.
process_begin: CreateProcess(NULL, mingw32-pkg-config --cflags purple, ...) failed.
process_begin: CreateProcess(NULL, i686-w64-mingw32-gcc -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra -fPIC -DPURPLE_PLUGINS -DPIC -I /pidgin/libpurple/ -I /win32-dev/gtk_2_0-2.14/include/glib-2.0/ -I /win32-dev/gtk_2_0-2.14/lib/glib-2.0/include/ -o wa_purple.o wa_purple.c, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make.exe: *** [wa_purple.o] Error 2
i686-w64-mingw32-gcc -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra -fPIC -DPURPLE_PLUGINS -DPIC   -I /pidgin/libpurple/ -I /win32-dev/gtk_2_0-2.14/include/glib-2.0/ -I /win32-dev/gtk_2_0-2.14/lib/glib-2.0/include/ -o wa_purple.o wa_purple.c
Makefile.mingw:48: recipe for target 'wa_purple.o' failed
Process terminated with status 2 (0 minute(s), 0 second(s))
1 error(s), 0 warning(s) (0 minute(s), 0 second(s))


How Fix it ?

**Comment by alikbn** [comment]
i not understand ...
all library copy coodeblocks\mingw
what to do for fix problem 
what missing?

**Comment by davidgfnet** [comment]
Please see https://davidgf.net/whatsapp/

**Comment by dequis** [comment]
Heh, interesting decision.

Update the README so that it doesn't link to 404'd pages? And you might want to write some FAQ about that.

**Comment by davidgfnet** [comment]
Updated Readme. I'm supporting 3 binary platforms... Guess that's enough.
