### ISSUE TITLE
compile files "Makefile.mingw"

### ISSUE THREAD

**Issue by axel21a** [davidgfnet/whatsapp-purple#202]
someone knows how to use the file "Makefile.mingw"
I have already installed the soft MinGW, I activated the system variables.
what are the commands to compile the library .dll (win7)
then if someone has already completed and makes it available, I think it's good for everyone, given that the site is no longer available.
thanks to all

**Comment by wvxoxg** [comment]
http://pastebin.com/KcaNJeCN

**Comment by Jeronimo17** [comment]
Very Good, Wvxoxg. I was going crazy looking libpurple-dev.

Thank you for explaining !!

**Comment by axel21a** [comment]
thanks so much.
as I said, I'm not a programmer, I'm trying to compile the .dll
for me it is very difficult, but we try, if I can not I will use the one already compilta.
is the latest version, the real 0.6.0
thanks again

**Comment by snDemon** [comment]
problem with compiling

-------------- Build: Debug in s (compiler: GNU GCC Compiler)---------------

Running command: mingw32-make.exe -f Makefile.mingw Debug
process_begin: CreateProcess(NULL, pkg-config --variable=plugindir purple, ...) failed.
process_begin: CreateProcess(NULL, pkg-config --variable=datarootdir purple, ...) failed.
mingw32-make.exe: *** No rule to make target 'Debug'.  Stop.
Process terminated with status 2 (0 minute(s), 0 second(s))
0 error(s), 0 warning(s) (0 minute(s), 0 second(s))

**Comment by Jeronimo17** [comment]
And to me that file I need?

..\wa_api.cc|446|warning: unused parameter 'waAPI' [-Wunused-parameter]|
..\wa_api.cc|446|warning: unused parameter 'phone' [-Wunused-parameter]|
..\wa_api.cc|671|warning: unused parameter 'filename' [-Wunused-parameter]|
..\wa_purple.o||In function `waprpl_xfer_cancel_send':|
C:\CodeBlocks\whatsapp-purple-master\wa_purple.c|1306|undefined reference to `purple_debug_info'|
..\wa_purple.o||In function `waprpl_xfer_end':|
C:\CodeBlocks\whatsapp-purple-master\wa_purple.c|1301|undefined reference to `purple_debug_info'|
..\wa_purple.o||In function `waprpl_xfer_start':|
C:\CodeBlocks\whatsapp-purple-master\wa_purple.c|1296|undefined reference to `purple_debug_info'|
..\wa_purple.o||In function `waprpl_new_xfer':|
C:\CodeBlocks\whatsapp-purple-master\wa_purple.c|1313|undefined reference to `purple_debug_info'|
C:\CodeBlocks\whatsapp-purple-master\wa_purple.c|1314|undefined reference to `purple_xfer_new'|
C:\CodeBlocks\whatsapp-purple-master\wa_purple.c|1316|undefined reference to `purple_connection_get_protocol_data'|
C:\CodeBlocks\whatsapp-purple-master\wa_purple.c|1318|undefined reference to `g_malloc0'|
C:\CodeBlocks\whatsapp-purple-master\wa_purple.c|1320|undefined reference to `g_strdup'|

**Comment by wvxoxg** [comment]
I thing I messed up with the libraries in that paste:
You need the following:
glib(Runtime & Dev), pkg-config(tool), gettext-runtime(Runtime)........................under GTK+ 2.x
and libpurple-dev

**Comment by axel21a** [comment]
so it must be also updated the tutorial you linked?

**Comment by wvxoxg** [comment]
Done

**Comment by snDemon** [comment]
thanks for help.... problem with compiling 
In the next step

------------

-------------- Build: Debug in s (compiler: GNU GCC Compiler)---------------

Running command: mingw32-make.exe -f Makefile.mingw Debug
mingw32-make.exe: *** No rule to make target 'Debug'.  Stop.
Process terminated with status 2 (0 minute(s), 0 second(s))
0 error(s), 0 warning(s) (0 minute(s), 0 second(s))

**Comment by wvxoxg** [comment]
Try this:
In the Menu Bar go to
Project->Build Option->"Make commands"->Built project/target: remove "$target"
So it looks like this: $make -f $makefile

**Comment by snDemon** [comment]
next step


-------------- Build: Debug in s (compiler: GNU GCC Compiler)---------------

Running command: mingw32-make.exe -f Makefile.mingw 
mingw32-make.exe: *** No rule to make target 'wa_purple.o', needed by 'libwhatsapp.dll'.  Stop.
Process terminated with status 2 (0 minute(s), 0 second(s))
0 error(s), 0 warning(s) (0 minute(s), 0 second(s))

**Comment by Jeronimo17** [comment]
Now it works, thanks again :)

**Comment by micaelsilva** [comment]
My builds keep failing:

Running command: mingw32-make.exe -f Makefile.mingw
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
mingw32-gcc -c -O2 -m32 -Wall -Wextra -fPIC -DPURPLE_PLUGINS -DPIC   -o wa_purple.o wa_purple.c
wa_purple.c:1:0: warning: -fPIC ignored for target (all code is position independent) [enabled by default]
wa_purple.c:35:18: fatal error: glib.h: No such file or directory
compilation terminated.
mingw32-make.exe: *** [wa_purple.o] Error 1
Process terminated with status 2 (0 minute(s), 0 second(s))
1 error(s), 1 warning(s) (0 minute(s), 0 second(s))

I understand that is because it can't find the dependency files, but I have no idea how I put this on the CodeBlocks PATH. Is this the same Windows PATH?

**Comment by wvxoxg** [comment]
Open cmd navigate to bin in Mingw folder (for me its: "cd C:\CodeBlocks\Mingw\bin") and type the following command: pkg-config --list-all

Atleast these 2 libraries should be listed in the result:
purple
glib-2.0

**Comment by snDemon** [comment]
i what to do .. for fix problem ??
-- Build: Debug in project 2 (compiler: GNU GCC Compiler)---------------

Running command: mingw32-make.exe -f Makefile.mingw 
mingw32-make.exe: *** No rule to make target 'wa_purple.o', needed by 'libwhatsapp.dll'.  Stop.

**Comment by micaelsilva** [comment]
There is no pkg-config on C:\CodeBlocks\Mingw\bin

**Comment by wvxoxg** [comment]
Then add it http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/pkg-config_0.26-1_win32.zip

**Comment by wvxoxg** [comment]
snDemon, you also check the libraries.

**Comment by micaelsilva** [comment]
To work the pkg-config required another .dll, in other bundle http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/gettext-runtime_0.18.1.1-2_win32.zip (found it out looking on google)

And now it works! Thank you so much for the help!

**Comment by snDemon** [comment]
check my libraries its done. all libraries  available  :|
my problem not fixed :((

**Comment by micaelsilva** [comment]
snDemon, did you check the Makefile.mingw if it's all correct?

**Comment by snDemon** [comment]
my project
http://wikisend.com/download/430596/project 2.rar
 can you check my project

**Comment by micaelsilva** [comment]
I think that your problem is the whole structure of diretories on the project. I've got the same problem but didn't mention it...

Try to create a new project this time inside the directory of the whatsapp code. When you add the code in CodeBlocks you'll see that the files will not be inside others subdirectories. Make sure that Makefile.mingw are not inside any other subdirectory too. Then make sure that "Execution directory" inside Project->Proprieties is pointing to the right folder where Makefile.mingw is.

**Comment by Edszx** [comment]
Can someone please provide an updated windows binary already compiled, please?

**Comment by snDemon** [comment]
Ok .. 
all makefile.ming remove.. 
added  C:\Program Files\CodeBlocks\MinGW
added adres "Execution directory"
http://www.uploadmb.com/dw.php?id=1420667481

But .. The same problem

can you upload your project ?

**Comment by micaelsilva** [comment]
The instructions said that you have to install CodeBlocks on C:\CodeBlocks not on C:\Program Files\CodeBlocks. This could be the reason for this problem.

The project is: http://www.uploadmb.com/dw.php?id=1420669806
The project file is on the libwa folder.

**Comment by snDemon** [comment]
i reinstall codeblocks...and install on c:\codeblocks

but .. not chaning enything
also ..the same problem

**Comment by wvxoxg** [comment]
snDemon I tried the project you uploaded.
Paste all the contents of whatsapp-purple-master into project 2 folder such that all the contents are in the same folder and the project will compile.

**Comment by snDemon** [comment]
very very thanks you
The problem was resolved

**Comment by Edszx** [comment]
Can someone please provide an updated windows binary already compiled?, i don't have access to a computer where i can install the required software to compile the dll myself.

**Comment by Jeronimo17** [comment]
look the end of "pastebin" of top :)

**Comment by Edszx** [comment]
Thanks @Jeronimo17 didn't saw that, and thanks to @wvxoxg too.

**Comment by davidgfnet** [comment]
Well I guess I can close this. The process I use to compile it for windows is the described in: https://developer.pidgin.im/wiki/BuildingWinPidgin
So what I do is I run this script: https://github.com/davidgfnet/pidgin-scripts
and after cross-compiling pidgin I just export the PIDGIN_DEV_ROOT variable to point to the previous folder. Make sure you softlink or rename pidgin-x.x.x to pidgin.
After this setup you can just type make -f Makefile.mingw and it should pick the appropriate libs and headers from the PIDGIN_DEV_ROOT folder, including the libpurple.dll
Hope this helps! I'm going to automate this anyway.

**Comment by Edszx** [comment]
@DecorousDeviser @Jeronimo17 @snDemon @axel21a @micaelsilva can any of you guys you please reupload windows libpurple-dev and the Custom Makefile referenced in the paste?

**Comment by micaelsilva** [comment]
@Edszx The libpurple is here: https://www.dropbox.com/s/dcysziqaf2hgbmv/libpurple.rar?dl=0
You can not trust the Makefile.mingw that was posted here because it has changed on the actual 0.7 version of the code. You'll have to get it and make the changes youll need to build it on CodeBlocks

**Comment by davidgfnet** [comment]
Ok locking
