### ISSUE TITLE
No package 'purple' found in pkg-config

### ISSUE THREAD

**Issue by shirishag75** [davidgfnet/whatsapp-purple#206]
I was trying to compile/make whatsapp-purple and came across this :-

    ~/games/whatsapp-purple$ make ARCH=x86_64
    Package purple was not found in the pkg-config search path.
    Perhaps you should add the directory containing `purple.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'purple' found
    Package purple was not found in the pkg-config search path.
    Perhaps you should add the directory containing `purple.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'purple' found
    Package purple was not found in the pkg-config search path.
    Perhaps you should add the directory containing `purple.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'purple' found
    gcc -c -m64 -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC  -o wa_purple.o wa_purple.c
    wa_purple.c:35:18: fatal error: glib.h: No such file or directory
     #include <glib.h>
                      ^
    compilation terminated.

Then I tried searching where purple.pc lives and found it lives in libpurple-dev :-

    /games/whatsapp-purple$ apt-file search purple.pc
    libpurple-dev: /usr/lib/pkgconfig/purple.pc

I installed it and ran the make/compilation again. 

This time it started compiling BUT there is no mention of needing libpurple-dev in the README.md . Please fix it.

**Comment by davidgfnet** [comment]
Yeah there is no dependencies listed in the readme, but you can look at travis.yml to see how to build it, don't you?
