### ISSUE TITLE
Migrate to dh_python2 instead of dh_pysupport 

### ISSUE THREAD

**Issue by shirishag75** [davidgfnet/whatsapp-purple#207]
Hi all, 
I was compiling the build using fakeroot and got the following :- 

    ~/games/whatsapp-purple$ fakeroot debian/rules binary
    debian/rules: line 1: fg: no job control
       dh_testroot
       dh_prep
       dh_installdirs
       dh_auto_install
    install -D libwhatsapp.so /data/shirish/Games/whatsapp-purple/debian/pidgin-whatsapp/usr/lib/purple-2/libwhatsapp.so
    install -D whatsapp16.png /data/shirish/Games/whatsapp-purple/debian/pidgin-whatsapp/usr/share/pixmaps/pidgin/protocols/16/whatsapp.png
    install -D whatsapp22.png /data/shirish/Games/whatsapp-purple/debian/pidgin-whatsapp/usr/share/pixmaps/pidgin/protocols/22/whatsapp.png
    install -D whatsapp48.png /data/shirish/Games/whatsapp-purple/debian/pidgin-whatsapp/usr/share/pixmaps/pidgin/protocols/48/whatsapp.png
       dh_installdocs
       dh_installchangelogs
       dh_pysupport
    dh_pysupport: This program is deprecated, you should use dh_python2 instead. Migration guide: http://deb.li/dhs2p
       dh_perl
       dh_link
       dh_compress
       dh_fixperms
       dh_strip
       dh_makeshlibs
       dh_shlibdeps
       dh_installdeb
       dh_gencontrol
    dpkg-gencontrol: warning: unknown information field 'Dm-Upload-Allowed' in input data in general section of control info file
       dh_md5sums
       dh_builddeb
    dpkg-deb: building package `pidgin-whatsapp' in `../pidgin-whatsapp_0.6_amd64.deb'.

As shared it needs to be :-

     dh_pysupport: This program is deprecated, you should use dh_python2 instead. Migration guide: http://deb.li/dhs2p

Could you please fix this ?

**Comment by davidgfnet** [comment]
make && sudo make install will work as well...
I haven't seen this problem yet, but I'm open to accept pull requests.

**Comment by shirishag75** [comment]
I am unfortunately not a programmer myself but those in the know have shared a migration guide at https://wiki.debian.org/Python/TransitionToDHPython2

This is about 1.5 year old guide but should be good.

**Comment by davidgfnet** [comment]
Anyone (apart from shirishag75) making sense of this? Otherwise I'm closing this right away.

**Comment by dequis** [comment]
Not getting that here in a debian jessie docker container.

```
Step 9 : RUN fakeroot debian/rules binary
 ---> Running in 8cde4aec8579
debian/rules: line 1: fg: no job control
   dh_testdir
   dh_auto_configure
   dh_auto_build
gcc -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -o wa_purple.o wa_purple.c
gcc -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -o tinfl.o tinfl.c
g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o whatsapp-protocol.o whatsapp-protocol.cc
g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o wa_api.o wa_api.cc
g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o rc4.o rc4.cc
g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o keygen.o keygen.cc
g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o tree.o tree.cc
g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o databuffer.o databuffer.cc
g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o message.o message.cc
g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o whatsapp_api.o whatsapp_api.cc
g++  -shared -pipe  -o libwhatsapp.so wa_purple.o tinfl.o whatsapp-protocol.o wa_api.o rc4.o keygen.o tree.o databuffer.o message.o whatsapp_api.o -lpurple -lglib-2.0
   dh_auto_test
   dh_testroot
   dh_prep
   dh_installdirs
   dh_auto_install
install -D libwhatsapp.so /tmp/whatsapp-purple/debian/pidgin-whatsapp/usr/lib/purple-2/libwhatsapp.so
install -D whatsapp16.png /tmp/whatsapp-purple/debian/pidgin-whatsapp/usr/share/pixmaps/pidgin/protocols/16/whatsapp.png
install -D whatsapp22.png /tmp/whatsapp-purple/debian/pidgin-whatsapp/usr/share/pixmaps/pidgin/protocols/22/whatsapp.png
install -D whatsapp48.png /tmp/whatsapp-purple/debian/pidgin-whatsapp/usr/share/pixmaps/pidgin/protocols/48/whatsapp.png
   dh_installdocs
   dh_installchangelogs
   dh_perl
   dh_link
   dh_compress
   dh_fixperms
   dh_strip
   dh_makeshlibs
   dh_shlibdeps
   dh_installdeb
   dh_gencontrol
dpkg-gencontrol: warning: unknown information field 'Dm-Upload-Allowed' in input data in general section of control info file
dpkg-gencontrol: warning: File::FcntlLock not available; using flock which is not NFS-safe
   dh_md5sums
   dh_builddeb
dpkg-deb: building package `pidgin-whatsapp' in `../pidgin-whatsapp_0.7_amd64.deb'.
 ---> 727acfa0dacb
Removing intermediate container 8cde4aec8579
Successfully built 727acfa0dacb
```

Also, it builds successfully.

It's probably a "bug" in OP's version of debhelper. Close this!

**Comment by davidgfnet** [comment]
Yep I thought so... Works great on launchpad for Ubuntu...

**Comment by shirishag75** [comment]
I purged debhelper and installed it, got the same thing. This lead to me to bugs.debian.org/634106 . I don't know python much but it seemed just increasing the compat level does the trick as can be seen. 

    $ fakeroot debian/rules clean
    debian/rules: line 1: fg: no job control
       dh_testdir
       dh_auto_clean
    rm -f *.o
    rm -f libwhatsapp.so
       dh_clean

~/games/whatsapp-purple$ fakeroot debian/rules binary
    debian/rules: line 1: fg: no job control
       dh_testdir
       dh_auto_configure
       dh_auto_build
    gcc -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -o wa_purple.o wa_purple.c
    gcc -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -o tinfl.o tinfl.c
    g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o whatsapp-protocol.o whatsapp-protocol.cc
    g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o wa_api.o wa_api.cc
    g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o rc4.o rc4.cc
    g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o keygen.o keygen.cc
    g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o tree.o tree.cc
    g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o databuffer.o databuffer.cc
    g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o message.o message.cc
    g++ -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libpurple  -std=c++11 -o whatsapp_api.o whatsapp_api.cc
    g++  -shared -pipe  -o libwhatsapp.so wa_purple.o tinfl.o whatsapp-protocol.o wa_api.o rc4.o keygen.o tree.o databuffer.o message.o whatsapp_api.o -lpurple -lglib-2.0 
       dh_auto_test
       dh_testroot
       dh_prep
       dh_installdirs
       dh_auto_install
    install -D libwhatsapp.so /data/shirish/Games/whatsapp-purple/debian/pidgin-whatsapp/usr/lib/purple-2/libwhatsapp.so
    install -D whatsapp16.png /data/shirish/Games/whatsapp-purple/debian/pidgin-whatsapp/usr/share/pixmaps/pidgin/protocols/16/whatsapp.png
    install -D whatsapp22.png /data/shirish/Games/whatsapp-purple/debian/pidgin-whatsapp/usr/share/pixmaps/pidgin/protocols/22/whatsapp.png
    install -D whatsapp48.png /data/shirish/Games/whatsapp-purple/debian/pidgin-whatsapp/usr/share/pixmaps/pidgin/protocols/48/whatsapp.png
       dh_installdocs
       dh_installchangelogs
       dh_perl
       dh_link
       dh_compress
       dh_fixperms
       dh_strip
       dh_makeshlibs
       dh_shlibdeps
       dh_installdeb
       dh_gencontrol
    dpkg-gencontrol: warning: unknown information field 'Dm-Upload-Allowed' in input data in general section of control info file
       dh_md5sums
       dh_builddeb    

~/games/whatsapp-purple/debian$ cat compat 
9

that's the only change I made, perhaps dx can share if this might be the thing needed to be done.
