### ISSUE TITLE
Kick someone off group?

### ISSUE THREAD

**Issue by ducklin5** [davidgfnet/whatsapp-purple#209]
as the question suggests, how exactly am i supposed to kick someone off a group if Im the admin? I believe there is a command i must enter

**Comment by davidgfnet** [comment]
I think it's not possible so far... But I think I remember doing this once ago...
Anyone? I'll try at home

**Comment by ducklin5** [comment]
Did you try? Any update on this?

**Comment by dequis** [comment]
@davidgfnet done something with this one already? If not, I'd like to work on it.

**Comment by davidgfnet** [comment]
Not yet. Seems there is no "standarized flow" to kick someone out of a room. We can implement this in many ways, but it's a shame that we haven't a flow for this (by flow I mean a libpurple call).
Should we discuss this on pidgin IRC @dequis?

**Comment by dequis** [comment]
A "kick" PurpleConversation command isn't enough? Not a great interface but it's what other protocol plugins (irc, silc and jabber) seem to do.

Also I just did this https://github.com/bitlbee/bitlbee/commit/e41cc4034741547c17ec4d24b9fdc50a8d2a5ee5

re IRC: sure, i'm always there, you're the one who isn't :D
