### ISSUE TITLE
Account settings don't change when plugin server/resource do

### ISSUE THREAD

**Issue by Zap123** [davidgfnet/whatsapp-purple#210]
I'm pretty sure this is a Pidgin problem because it's the same in other plugins, but it may helpful to write a notice somewhere.
Since weeks I started losing messages and I found that in account/advanced I still had server "c3.whatsapp.net", I changed account settings to whatever it's default in the source file and now it works flawless as always.
So if anyone is a long time user of this plugin and is having problem with messaging, could be helpful to check that or delete configuration (but then you lose contacts I guess).

P.S: It's not related to this issue, but I found this apk to extract whatsapp password and it would be nice to add it to the wiki.
https://github.com/venomous0x/WhatsAPI/issues/983

**Comment by davidgfnet** [comment]
Thanks for the info. I still do not get your issue. If user settings are wrong there is little we can do. As always "user being dumb" is something we cannot prevent.

**Comment by dequis** [comment]
Not so much "user being dumb", but "user not getting the fixed resource after upgrading". But like you said, not much that can be done, except maybe... adding a notice to the changelog if/when this happens again?

**Comment by davidgfnet** [comment]
:)
