### ISSUE TITLE
makefile.mingw Problem 

### ISSUE THREAD

**Issue by alikbn** [davidgfnet/whatsapp-purple#211]
hi 
i try to compile on coodeblock
But i have some problem 

---------------------------------build log----------------

-------------- Build: Debug in whatsapp (compiler: GNU GCC Compiler)---------------

Running command: mingw32-make.exe -f Makefile.mingw  
process_begin: CreateProcess(NULL, mingw32-pkg-config --variable=plugindir purple, ...) failed.
process_begin: CreateProcess(NULL, mingw32-pkg-config --variable=datarootdir purple, ...) failed.
process_begin: CreateProcess(NULL, mingw32-pkg-config --cflags purple, ...) failed.
process_begin: CreateProcess(NULL, i686-w64-mingw32-gcc -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra -fPIC -DPURPLE_PLUGINS -DPIC -I /pidgin/libpurple/ -I /win32-dev/gtk_2_0-2.14/include/glib-2.0/ -I /win32-dev/gtk_2_0-2.14/lib/glib-2.0/include/ -o wa_purple.o wa_purple.c, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make.exe: *** [wa_purple.o] Error 2
i686-w64-mingw32-gcc -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra -fPIC -DPURPLE_PLUGINS -DPIC   -I /pidgin/libpurple/ -I /win32-dev/gtk_2_0-2.14/include/glib-2.0/ -I /win32-dev/gtk_2_0-2.14/lib/glib-2.0/include/ -o wa_purple.o wa_purple.c
Makefile.mingw:48: recipe for target 'wa_purple.o' failed
Process terminated with status 2 (0 minute(s), 1 second(s))
1 error(s), 0 warning(s) (0 minute(s), 1 second(s))

**Comment by davidgfnet** [comment]
Dup #197
