### ISSUE TITLE
Not able to see the extension on pidgin.

### ISSUE THREAD

**Issue by shirishag75** [davidgfnet/whatsapp-purple#213]
Hi all, 
If I understood it right, after installing pidgin-whatsapp it should be in pidgin-whatsapp right, but it isn't :(

    $ dpkg -L pidgin-whatsapp 
    /.
    /usr
    /usr/lib
    /usr/lib/purple-2
    /usr/lib/purple-2/libwhatsapp.so
    /usr/share
    /usr/share/doc
    /usr/share/doc/pidgin-whatsapp
    /usr/share/doc/pidgin-whatsapp/copyright
    /usr/share/doc/pidgin-whatsapp/changelog.gz
    /usr/share/pixmaps
    /usr/share/pixmaps/pidgin
    /usr/share/pixmaps/pidgin/protocols
    /usr/share/pixmaps/pidgin/protocols/16
    /usr/share/pixmaps/pidgin/protocols/16/whatsapp.png
    /usr/share/pixmaps/pidgin/protocols/22
    /usr/share/pixmaps/pidgin/protocols/22/whatsapp.png
    /usr/share/pixmaps/pidgin/protocols/48
    /usr/share/pixmaps/pidgin/protocols/48/whatsapp.png

The pidgin windows shows all other plugins except this one, if needed can share a screenshot of the various plugins it shows.

**Comment by Zap123** [comment]
You see it in protocols when you create a new account. You don't see it from there?

**Comment by shirishag75** [comment]
My bad, didn't know it was in 'protocols', it is and I see it.
