### ISSUE TITLE
Is the PPA repository functioning and is there an IRC channel for the library ?

### ISSUE THREAD

**Issue by shirishag75** [davidgfnet/whatsapp-purple#214]
I wanted to see if the PPA repository is functioning but launchpad doesn't show anything 

https://code.launchpad.net/~whatsapp-purple is empty 

actually everything in whatsapp-purple is empty. 

If it's not happening then whoever has access please remove that info. from the README. 

Also if there is an IRC channel or something, please share those details.

**Comment by dequis** [comment]
The correct link is in the readme, https://launchpad.net/~whatsapp-purple/+archive/ubuntu/ppa

It has a package for 0.7 right there and instructions on how to add it to your system in "Adding this PPA to your system"

That page you linked is for source code repos hosted by launchpad, but the code is here in github.

There's no irc channel specific to whatsapp-purple but #pidgin in freenode is something. I'm there (with nick "dx") and sometimes answer questions, but most people in that channel know nothing about this plugin, so YMMV. @davidgfnet sometimes joins too but not very often.

**Comment by davidgfnet** [comment]
Use instructions at https://davidgf.net/whatsapp
Trying things and learning is usually a better option than just asking... And it helps making me less pissed of.
