### ISSUE TITLE
[Sorry the way to comunicate] Full emoji for pidgin and whatsapp-purple

### ISSUE THREAD

**Issue by tomascastana** [davidgfnet/whatsapp-purple#215]
Sorry the way, i'm new with github and i have not idea how to comunicate with @davidgfnet
I make a full set of emoji emoticons from whatsapp.apk and so much google, with all the correct unicodes values.
https://github.com/tomascastana/whatsapp-emoji-para-pidgin
You can download from that link. I don't want to make spam, i only want to share this. I worked a lot for get this set.

I hope you enjoy it.
Thanks!!

**Comment by davidgfnet** [comment]
Hehe,
Sorry to see that you invested so much time into that, but there are many places where you can get those emoji from. Just search for "pidgin emoji" on github to see..

Thanks anyway.
