### ISSUE TITLE
Can't retrieve password

### ISSUE THREAD

**Issue by maicomstoppa** [davidgfnet/whatsapp-purple#219]
Trying to get my Whatsapp password at https://davidgf.net/whatsapp/pwd.html gives me an "Internal server error (500)" within ajax request, making impossible to setup the account at Pidgin.

Do I have another alternative to acomplish this?

Thanks.

**Comment by davidgfnet** [comment]
You may want to use WART:

https://github.com/shirioko/WART/raw/master/WART-1.7.3.0.exe

**Comment by maicomstoppa** [comment]
I'll give it a try right now. 
Thanks, dude.

**Comment by maicomstoppa** [comment]
Worked flawless.
Resolved.
