### ISSUE TITLE
Adding / importing contacts

### ISSUE THREAD

**Issue by sokisorgenkind** [davidgfnet/whatsapp-purple#22]
Hey there,

first of all thank you for making this plugin available for us.

i managed to login into my whatsapp account using and i am directly seeing the groups... so far so good...  but how can i a) add contacts and/or b) import contacts?

thanks in advance and sorry if i missed some howto or page, where this has already been issued.

greetz
soki

EDIT: sry, seems i got just some kind of bug... now the option of adding a contact is available. thanks.

**Comment by iuliuss** [comment]
@davidgfnet 
I've used your plug-in and works great. Thanks!
Now I want to import my google contacts in whatsapp but I dont know how. I'm using a windows platform. The links provided for ContactSync are not working.Can you please provide a new valid link.
Any suggestion about how to easy import the contacts will be very appreciated. Thanks.

**Comment by kafinetetaha** [comment]
https://github.com/shirioko/WhatsAPINet/blob/master/WhatsAppApi/Helper/ContactSync.cs
file not found??????

**Comment by maneesh654** [comment]
I wanna sync my google contacts with Pidgin someone help, Please.
