### ISSUE TITLE
My own name and number are not binded. 

### ISSUE THREAD

**Issue by shirishag75** [davidgfnet/whatsapp-purple#220]
Hi all, 
My own name and number are not binded. Is there a way around it ? I have encountered this esp. in chats.

**Comment by dequis** [comment]
>not binded

what does that even mean

**Comment by davidgfnet** [comment]
Hey dude, why do you report the same issue 2 times? It's not the first time you do so, please do not do it again. I don't want to report more spammers to github.

**Comment by shirishag75** [comment]
I don't think I reported the same issue, If I have done that inadvertently, then sorry and please tell me the bug/ticket number so I will follow that religiously. 

@dequis  - by not binding, as far as I understand, what people do is when people see your number, they should be seeing the name and not the number. In their contact list they are able to see only the number, not name, nor profile pic. While the profile pic. part is already covered/known in #105 but  not anything else. There is also #78 which talks of not being able to see the other person's name but only their  contact numbers. 

I do not know if seeing other people's contact numbers and other people not being able to see my name/alias is the same bug/ticket or not hence reported it here.
