### ISSUE TITLE
Compiling under windows MakeAttr Macro error (wacommon.h)

### ISSUE THREAD

**Issue by Tzaoh** [davidgfnet/whatsapp-purple#221]
I include all the files and edit Makefile.mingw. I got this error 4 times during compilation.
aparently there is something wrong in wacommon.h in the macros MakeAttr{1, 2, 3, 4, 5}

whatsapp-protocol.cc|56|error: no matching function for call to 'std::map<std::basic_string<char>, std::basic_string<char> >::map(<brace-enclosed initializer list>)'|

Build messages: http://pastebin.com/2Mnxh47d

**Comment by davidgfnet** [comment]
Something related to "std=c++11"? Which compiler version are you using?

**Comment by Tzaoh** [comment]
C:\CodeBlocks\MinGW\bin>gcc --version
gcc (tdm-1) 4.7.1
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


C:\CodeBlocks\MinGW\bin>g++.exe --version
g++.exe (tdm-1) 4.7.1
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Tzaoh** [comment]
Oh, I see i will try it this afternoon gracias salao!

**Comment by davidgfnet** [comment]
Any update? Or I shall close this otherwise

**Comment by annonbacca** [comment]
@Tzaoh 

Hey could you upload your Makefile.mingw. I am trying to compile it the latest source code and seem to be stuck.

**Comment by annonbacca** [comment]
Disregard that, I think it works, I just found my libwhatsapp.dll in the source directory freshly compiled. Took me hours to sort this one out but I would just like to confirm that It works.

Was using a similar GCC version to Tzaoh, gcc (tdm-1) 4.7.1
and I changed change std=c++11 to std=gnu++11
