### ISSUE TITLE
Workaround for spectrum-users-dont-come-online-problem?

### ISSUE THREAD

**Issue by hpmueller1971** [davidgfnet/whatsapp-purple#222]
Hi,

i've seen various bugs reports that users don't come online when using spectrum with whatsapp-purple, with every single contact i have to re-request the autorisation from the xmpp-client to see the status, but sadly noone seems to know the exact cause of this problem (as it does work with the real pidgin).

Does someone have a fix or workaround for this problem? Can't the plugin do (via a compile option or something) the same thing that happens, when i ask for authorisation, on every whatsapp-user when a purple-user comes online? I compile from source anyway, so i would not care if it's just a dirty patch that will not get integrated into git, just has to work ;)...

**Comment by davidgfnet** [comment]
Hey dude, you're right, you've seen many issues before. Why opening a new one? I don't wanna be unpolite but I think I already lost patience with this behavior.
Dup #70
