### ISSUE TITLE
Unable to reach work with pidgin/whatsapp

### ISSUE THREAD

**Issue by seenutn** [davidgfnet/whatsapp-purple#226]
Hi,
   I had the whatsapp plugin working with pidgin on Ubuntu 14.04.  Previously it had stopped working and later changed according to what I have mentioned in https://github.com/davidgfnet/whatsapp-purple/issues/73 (comment by me on 29th Nov 2014).  But today (25th Feb), it has again stopped working.  I don't see the string in accounts.xml previously I mentioned and now it has Android-4.0.4.  I even updated the package and still the problem exists.

seenutn@om:~/.purple$ apt-cache show pidgin-whatsapp
Package: pidgin-whatsapp
Priority: optional
Section: net
Installed-Size: 367
Maintainer: David Guillen Fandos <david@davidgf.net>
Architecture: amd64
Version: 0.7

Any idea about what could be done to make it work again?

**Comment by dequis** [comment]
See #224

**Comment by seenutn** [comment]
Thanks for pointing it out.  I have added my comments to the above issue.
