### ISSUE TITLE
how to attach multiple images at once

### ISSUE THREAD

**Issue by sant527** [davidgfnet/whatsapp-purple#228]
I am using archlinux and pidgin. Recently insalled whatsapp-purple. It simply great. I am looking for a way to send multiple images at once to a buddy. Because in pigin its allowing only one image one time

**Comment by davidgfnet** [comment]
Hello! Unless you send 100 images at a time... it's not worth considering.
Anyway this is a Pidgin-specific issue and thus makes no sense to discuss this here. Ask on #pidgin channel on freenode IRC.

**Comment by sant527** [comment]
Ok
