### ISSUE TITLE
message sent via broadcasts show different number

### ISSUE THREAD

**Issue by sant527** [davidgfnet/whatsapp-purple#232]
If some send a message from their broadcast list. Then the message shows as if coming from  a broadcast id instead of the number of the person who sends it

Example 993434340 send message to 87788888  through his braodcast list. the message is shown as coming from 144545545 to 87888888 instead 993434340.

**Comment by davidgfnet** [comment]
I've never used broadcast. I guess I'll have to try this, since it seems it's using a groupchat-like method to send the messages. Thanks for the heads up!

**Comment by shirishag75** [comment]
Is there a UI for broadcast lists ? I didn't see. Only see regular lists that one can make.  Saw what broadcast lists are all about http://www.whatsapp.com/faq/en/android/23130793

**Comment by dequis** [comment]
Nope, only receiving for now, and honestly I have no idea how that feature would fit in libpurple.

**Comment by shirishag75** [comment]
@dequis how do I know if I am receiving a broadcast message, if I'm not mistaken it would look just like normal messages, right ?
