### ISSUE TITLE
unable to fetch 14.10

### ISSUE THREAD

**Issue by rakshitsakhuja** [davidgfnet/whatsapp-purple#233]
this is not working for 14.10 utopic
W: Failed to fetch http://ppa.launchpad.net/whatsapp-purple/ppa/ubuntu/dists/utopic/main/binary-amd64/Packages  404  Not Found                 

W: Failed to fetch http://ppa.launchpad.net/whatsapp-purple/ppa/ubuntu/dists/utopic/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

this is the exact error message

**Comment by davidgfnet** [comment]
Hello @rakshitsakhuja you should not post this in here, it's an ubuntu specific thing. This should be reported in launchpad. The 404 is due to the fact that packages for 14.10 haven't been added.
