### ISSUE TITLE
Web access [enhancement]

### ISSUE THREAD

**Issue by jjeziorny** [davidgfnet/whatsapp-purple#239]
Now that whatsapp has a web app access it would be great if the plugin could use that as it allows for connection from the PC and Mobile simultaneously.

**Comment by davidgfnet** [comment]
From my infinite ignorance... Why do you want the plugin if you can use the
web? Just sayin...

**Comment by jjeziorny** [comment]
Errrrrrrr,  so I can have the whatsapp conversations inside pidgin a s not 
in a Web page


----------

**Comment by namoplasta** [comment]
@davidgfnet 
https://web.whatsapp.com/

I think I understand what he meant, he wants a way to authenticate the QR code on whatsapp-purple for use on whatsapp web.

I think there may have functions that do not have whatsapp purple, as setting the avatar and name and etc, never used whatsappweb, but I'm curious :), if interesting, this would be a good implementation.

**Comment by dequis** [comment]
I suggested this in [a different ticket][0], quoting myself here for context:

>Maybe creating a 'whatsapp web' client isn't a bad idea after all... I wrote [some notes][1] about it, only good enough as an introduction/overview, but there's plenty of stuff left to reverse to achieve a working third party client for that. It's also completely different from this plugin... And I mentioned it there, but there's a restriction to only one web client at the same time (the others get in a pause-like mode, and gotta implement a way to takeover the mutex)

Emphasis here: **It's also completely different from this plugin**

@davidgfnet's reply:

>What you say sounds interesting but IMO this defies the whole purpose of all of this which is getting rid of the official client. The main consumers of this plugin seem to be people not having an smartphone at all.

But yeah, since none of the code of this plugin will be useful for web access, this is like requesting a whole new project.

[0]: https://github.com/davidgfnet/whatsapp-purple/issues/224#issuecomment-77788965
[1]: http://wiki.dequis.org/notes/whatsapp_web/

**Comment by davidgfnet** [comment]
Yep, as dequis says, unrelated to this project. If someone wants to implement it, go ahead! You got my support, but not me sorry :D
Closing!

**Comment by radasbona** [comment]
I'm looking for a WA-Web plugin for libpurple and found this tread via google. Does anyone knows something usable?
