### ISSUE TITLE
Server closed the connection

### ISSUE THREAD

**Issue by mborasso** [davidgfnet/whatsapp-purple#243]
Recently I can't connect pidgin with my Whatsapp account: in the main page I see this sentence "Server closed the connection".

So far I used this configuration without problems:

SERVER: c2.whatsapp.net
PORT: 5222
RESOURCE: WP7-2.11.596-443

I have PIDGIN libpurple 2.10.11.

Could you help me?

**Comment by dequis** [comment]
See #224. tl;dr they probably banned your number.
