### ISSUE TITLE
A empty conversation group apparear after login

### ISSUE THREAD

**Issue by angelbladex** [davidgfnet/whatsapp-purple#244]
i compiled today recent version of plugin. i solved installing freeimage because i didn't have this package.

Now , when i open pidgin i have always active Whatsapp. 
Afer compile, if i open pidgin, after connect, apparear a window, a empty conversation from a group i belong. I  detect one line strange in log vía pidgin -d 

....
(20:32:42) proxy: Attempting connection to 173.192.222.185
(20:32:42) proxy: Connecting to c3.whatsapp.net:443 with no proxy
(20:32:42) proxy: Connection in progress
(20:32:42) proxy: Connecting to c3.whatsapp.net:443.
(20:32:42) proxy: Connected to c3.whatsapp.net:443.
(20:32:43) whatsapp: joining group AGroup
(20:32:43) gtkconv: setting active conversation on toolbar 0x8fe8a08
(20:32:43) gtkconv: setting active conversation on toolbar 0x8fe8a08
(20:32:43) prefs: /pidgin/conversations/toolbar/wide changed, scheduling save.
(20:32:43) whatsapp: group info ID(58OwnerGroup-ID) SUBJECT(Unknown) OWNER(000000) << (?)
(20:32:43) blist: Updating buddy status for 58aFriend (WhatsApp)
.....

**Comment by davidgfnet** [comment]
You are probably receiving a notification "join" stanza. Can you compile
(make debug) and paste the stanzas you see? Look for the group ID (or
just paste everythin).

Cheers

**Comment by angelbladex** [comment]
Ok. 

i made a new compilation and log have like this. I edit my number and other values. i add comments 

21:56:57) account: Connecting to account 58MyNumber.
(21:56:57) connection: Connecting. gc = 0x8bf9bc8
(21:56:57) whatsapp: logging in 58MyNumber
(21:56:57) dnsquery: Performing DNS lookup for c3.whatsapp.net
(21:56:57) dns: Created new DNS child 11803, there are now 1 children.
(21:56:57) dns: Successfully sent DNS request to child 11803
(21:56:57) docklet: embedded
(21:56:57) prefs: /pidgin/docklet/gtk/embedded changed, scheduling save.
(21:56:57) dns: Got response for 'c3.whatsapp.net'
(21:56:57) dnsquery: IP resolved for c3.whatsapp.net
(21:56:57) proxy: Attempting connection to 184.173.147.52
(21:56:57) proxy: Connecting to c3.whatsapp.net:443 with no proxy
(21:56:57) proxy: Connection in progress
(21:56:57) proxy: Connecting to c3.whatsapp.net:443.
(21:56:57) proxy: Connected to c3.whatsapp.net:443.
Tag: start
at[resource]=Android-2.31.151-443
at[to]=s.whatsapp.net
Data:  ...

Tag: stream:features
Data:  ...
 Tag: readreceipts
 Data:  ...
 Tag: privacy
 Data:  ...
 Tag: presence
 Data:  ...
 Tag: groups_v2
 Data:  ...

Tag: auth
at[mechanism]=WAUTH-2
at[user]=58MyNumber
Data:  ...

Tag: start
at[from]=s.whatsapp.net
Data:  ...

Tag: stream:features
Data:  ...

Tag: challenge
Data: çëã9¼{| ...

Tag: response
Data: >ÂÚ/Ù ...

Tag: success
at[creation]=1378773300
at[expiration]=1441845300
at[kind]=free
at[props]=4
at[status]=active
at[t]=1427768819
Data: µîðxgßb ...

Tag: presence
at[name]=LuisG ( @angelbladex )
at[type]=available
Data:  ...

Tag: iq
at[id]=1
at[to]=s.whatsapp.net
at[type]=get
at[xmlns]=privacy
Data:  ...
 Tag: privacy
 Data:  ...

Tag: iq
at[id]=2
at[to]=s.whatsapp.net
at[type]=get
at[xmlns]=urn:xmpp:whatsapp:push
Data:  ...
 Tag: config
 Data:  ...

Tag: iq
at[id]=3
at[to]=g.us
at[type]=get
at[xmlns]=w:g
Data:  ...
 Tag: list
 at[type]=owning
 Data:  ...

Tag: iq
at[id]=4
at[to]=g.us
at[type]=get
at[xmlns]=w:g
Data:  ...
 Tag: list
 at[type]=participating
 Data:  ...

Logged in!!!
(21:56:57) whatsapp: joining group Labcomp ðîî«
(21:56:57) gtkconv: setting active conversation on toolbar 0x8bf73f0
(21:56:57) gtkconv: setting active conversation on toolbar 0x8bf73f0
(21:56:58) prefs: /pidgin/conversations/toolbar/wide changed, scheduling save.
(21:56:58) whatsapp: group info ID(58OwnerGroup-1404439597) SUBJECT(Unknown) OWNER(000000)
Tag: presence
at[to]=ConctactNumber@s.whatsapp.net
at[type]=subscribe
Data:  ...


----Info for each contact 
Tag: iq
at[id]=5....48 (i have 48 contacts.. i hide theirs numbers)
at[to]=Contact1@s.whatsapp.net
at[type]=get
at[xmlns]=w:profile:picture
Data:  ...
 Tag: picture
 at[type]=preview
 Data:  ...

Tag: iq
at[id]=1427768818-52
at[to]=s.whatsapp.net
at[type]=set
at[xmlns]=status
Data:  ...
 Tag: status
 Data: @Casa ...
---for each contact on My contacts, this line apparear----
(21:56:58) blist: Updating buddy status for 58MyContact (WhatsApp)
.
.
.
.
Tag: ib
at[from]=s.whatsapp.net
Data:  ...
 Tag: dirty
 at[timestamp]=1413559081
 at[type]=groups
 Data:  ...

Tag: ib
at[from]=s.whatsapp.net
Data:  ...
 Tag: offline
 at[count]=0
 Data:  ...

Tag: presence
at[from]=58MyNumber@s.whatsapp.net
Data:  ...

Tag: iq
at[from]=g.us
at[id]=3
at[type]=error
Data:  ...
 Tag: error
 at[code]=500
 at[text]=internal-server-error
 Data:  ...

Tag: iq
at[from]=g.us
at[id]=4
at[type]=result
Data:  ...
 Tag: group
 at[creation]=1404439597
 at[id]=58OwnerGroup-1404439597
 at[owner]=58OwnerGroup@s.whatsapp.net
 at[s_o]=58LastOwnerGroup@s.whatsapp.net
 at[s_t]=1404439908
 at[subject]=Labcomp ðîî« // my group always have this character and the plugin work well.
 Data:  ...

Tag: iq
at[id]=53
at[to]=58OwnerGroup-1404439597@g.us
at[type]=get
at[xmlns]=w:g
Data:  ...
 Tag: list
 Data:  ...

(21:56:58) whatsapp: Receiving update information from my groups
Tag: iq
at[from]=58???????@s.whatsapp.net  <<< This owner of group,i know this contact, but i'm on 1 group, error for data (??) or error for add other group
at[id]=7
at[type]=result
Data:  ...
 Tag: picture
 at[id]=1425818423
 at[type]=preview
 Data: ÿØÿà     <<<< (???)

**Comment by davidgfnet** [comment]
That is very strange... I don't see whay you should be seeing any empty window. There is no notification, no messages,... Can you post an screenshot?

**Comment by angelbladex** [comment]
Ok.

When open main windows, apparear empty windows from the gruoup i belong


![a](https://cloud.githubusercontent.com/assets/847922/6922476/2ee13242-d795-11e4-897a-4dd8a333e695.jpg)

**Comment by davidgfnet** [comment]
Some questions:
- When you receive a message in that group, can you read it?
- When you close pidgin and reopen it are you 100% sure that no messages
have been sent to the group during that small period of time? (It might be
some message is being sent but it doesn't show up).
- Do you have other groups? Is it always happening with this one?

Thanks

**Comment by angelbladex** [comment]
-The group is inactive,  without messages from last Friday. i make queries to member from this group
-Always can read messages before last compilation. 
-This is my only group but debug suggest me i am on other group too. i need verify this asking.

**Comment by pabloscasas** [comment]
In my case it happens the same: an empty group conversation is open each time I connect to the server.

**Comment by davidgfnet** [comment]
Uhm, strange. Can you please try to deinstall it (and remove all user data, blist.xml) and try again? It happened to me whenI was trying to fix groups. The problem is that the config is not always backwards compatible. I should probably try to fix this weird corner cases.

**Comment by angelbladex** [comment]
Update: Im dont receiving message from my group, i tested send a message, the group received but i dont get response :S

**Comment by pabloscasas** [comment]
davidgfnet, removing blist.xml means losing all the contacts for all pidgin accounts. Isn't there a less harmful test?
In my case I loose every message sent to a group when I am disconnected.

**Comment by davidgfnet** [comment]
Make a backup!
Just try it for a while and see if that solves the problem. Then you can restore the backup.

**Comment by angelbladex** [comment]
I saw a change when make a backup with this steps

-Disable other accounts on Pidgin, specially accounts dont save contacts on blist.xml . Let Whatsapp enabled 
-Close Pidgin. 
-Save a copy of blist.xml . On Linux the file is on $HOME/.purple/blist.xml
-Delete blist.xml
-Open Pidgin

Whatsapp connected to Internet and didnt show me empty conversation from groups, but i have 58 contacts for add manually :S When join to group apparear a message like "You dont belong to this group....."

**Comment by angelbladex** [comment]
Ok. Empty windows apparears when group have the option "Connect automatically". Remember this option dont bother before :S

Now, need some day for confirm #261
