### ISSUE TITLE
Repeated Disconnection Notification after recieving Whatsapp Call

### ISSUE THREAD

**Issue by annonbacca** [davidgfnet/whatsapp-purple#246]
So, I tested calling my other number, using an official whatsapp client to a pidgin plugin and I noticed I kept getting sign-on notifications. So, I would just like to caution against receiving whatsapp calls if you are using whatsapp-purple.

**Comment by davidgfnet** [comment]
I'll submit a patch soon. I sniffed the traffic the other day and it seems pretty easy. Maybe I can even reverse the calling protocol. AFAIK it uses RTSP.

**Comment by davidgfnet** [comment]
This should be fixed as of last commit. The problem is that we did not sent an ACK after receiving a calm request.
