### ISSUE TITLE
Cant Compile installer.nsi

### ISSUE THREAD

**Issue by unnamedXD** [davidgfnet/whatsapp-purple#248]
I get this error message when I try to compile the installer.nsi file with  NSIS 3.0b1 from (http://nsis.sourceforge.net/Download)
this is the error message 
"File: "deps/*.dll" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)

Error in script "D:\whatsapp-purple\win32\installer.nsi" on line 94 -- aborting creation process"

**Comment by davidgfnet** [comment]
dep/ should contain DLL files such as freeimage.
