### ISSUE TITLE
libwhatsapp.dll is unknown

### ISSUE THREAD

**Issue by G0Y0** [davidgfnet/whatsapp-purple#253]
After compiling the source code whatsapp-purple , loading the library libwhatsapp.dll Pigin not work and my account WhatsApp goes as unknown. I have many warnings when compiling , must be why , but not how to fix it . This is what I get when compiling:

C:\whatsapp-purple-master>mingw32-make -f Makefile.mingw
i686-w64-mingw32-gcc -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra
-fPIC -DPURPLE_PLUGINS -DPIC -IC:/mingw32/pidgin/libpurple    -I "/pidgin/libpur
ple/" -I "/win32-dev/gtk_2_0-2.14/include/glib-2.0/" -I "/win32-dev/gtk_2_0-2.14
/lib/glib-2.0/include/" -o wa_purple.o wa_purple.c
cc1.exe: warning: command line option '-std=c++11' is valid for C++/ObjC++ but n
ot for C
wa_purple.c:1:0: warning: -fPIC ignored for target (all code is position indepen
dent)
 /**
 ^
wa_purple.c: In function 'hasht_cmp_convo':
wa_purple.c:336:60: warning: comparison between signed and unsigned integer expr
essions [-Wsign-compare]
  return (chatid_to_convo(g_hash_table_lookup(hasht, "id")) == *((int *)data));
                                                            ^
wa_purple.c: In function 'waprpl_output_cb':
wa_purple.c:691:3: warning: implicit declaration of function 'wpurple_write' [-W
implicit-function-declaration]
   ret = sys_write(wconn->fd, tempbuff, datatosend);
   ^
wa_purple.c: In function 'waprpl_input_cb':
wa_purple.c:718:3: warning: implicit declaration of function 'wpurple_read' [-Wi
mplicit-function-declaration]
   ret = sys_read(wconn->fd, tempbuff, sizeof(tempbuff));
   ^
wa_purple.c: In function 'waprpl_close':
wa_purple.c:850:3: warning: implicit declaration of function 'wpurple_close' [-W
implicit-function-declaration]
   sys_close(wconn->fd);
   ^
wa_purple.c: In function 'waprpl_xfer_init':
wa_purple.c:1385:2: warning: unknown conversion type character 'z' in format [-W
format=]
  purple_debug_info(WHATSAPP_ID, "Transfer file %s at %s with size %zu (given re
f %d)\n", fn, fp, fs, xfer_info->ref_id);
  ^
wa_purple.c:1385:2: warning: too many arguments for format [-Wformat-extra-args]

i686-w64-mingw32-gcc -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra
-fPIC -DPURPLE_PLUGINS -DPIC -IC:/mingw32/pidgin/libpurple    -I "/pidgin/libpur
ple/" -I "/win32-dev/gtk_2_0-2.14/include/glib-2.0/" -I "/win32-dev/gtk_2_0-2.14
/lib/glib-2.0/include/" -o tinfl.o tinfl.c
cc1.exe: warning: command line option '-std=c++11' is valid for C++/ObjC++ but n
ot for C
tinfl.c:1:0: warning: -fPIC ignored for target (all code is position independent
)
 /* tinfl.c v1.11 - public domain inflate with zlib header parsing/adler32 check
ing (inflate-only subset of miniz.c)
 ^
i686-w64-mingw32-gcc -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra
-fPIC -DPURPLE_PLUGINS -DPIC -IC:/mingw32/pidgin/libpurple    -I "/pidgin/libpur
ple/" -I "/win32-dev/gtk_2_0-2.14/include/glib-2.0/" -I "/win32-dev/gtk_2_0-2.14
/lib/glib-2.0/include/" -o imgutil.o imgutil.c
cc1.exe: warning: command line option '-std=c++11' is valid for C++/ObjC++ but n
ot for C
imgutil.c:1:0: warning: -fPIC ignored for target (all code is position independe
nt)

 ^
imgutil.c: In function 'imgProfile':
imgutil.c:10:45: warning: passing argument 1 of 'FreeImage_OpenMemory' discards
'const' qualifier from pointer target type
  FIMEMORY * inimgmem = FreeImage_OpenMemory(data, size);
                                             ^
In file included from imgutil.c:2:0:
C:/mingw32/i686-w64-mingw32/include/FreeImage.h:825:32: note: expected 'BYTE *'
but argument is of type 'const unsigned char *'
 DLL_API FIMEMORY *DLL_CALLCONV FreeImage_OpenMemory(BYTE *data FI_DEFAULT(0), D
WORD size_in_bytes FI_DEFAULT(0));
                                ^
imgutil.c: In function 'imgThumbnail':
imgutil.c:53:45: warning: passing argument 1 of 'FreeImage_OpenMemory' discards
'const' qualifier from pointer target type
  FIMEMORY * inimgmem = FreeImage_OpenMemory(data, size);
                                             ^
In file included from imgutil.c:2:0:
C:/mingw32/i686-w64-mingw32/include/FreeImage.h:825:32: note: expected 'BYTE *'
but argument is of type 'const unsigned char *'
 DLL_API FIMEMORY *DLL_CALLCONV FreeImage_OpenMemory(BYTE *data FI_DEFAULT(0), D
WORD size_in_bytes FI_DEFAULT(0));
                                ^
i686-w64-mingw32-g++ -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra
-fPIC -DPURPLE_PLUGINS -DPIC -IC:/mingw32/pidgin/libpurple    -I "/pidgin/libpur
ple/" -I "/win32-dev/gtk_2_0-2.14/include/glib-2.0/" -I "/win32-dev/gtk_2_0-2.14
/lib/glib-2.0/include/" -o whatsapp-protocol.o whatsapp-protocol.cc
whatsapp-protocol.cc:1:0: warning: -fPIC ignored for target (all code is positio
n independent)

 ^
In file included from wa_connection.h:9:0,
                 from whatsapp-protocol.cc:38:
wacommon.h: In function 'long long unsigned int str2lng(std::string)':
wacommon.h:16:31: warning: format '%u' expects argument of type 'unsigned int*',
 but argument 3 has type 'long long unsigned int*' [-Wformat=]
  sscanf(s.c_str(), "%I64u", &r);
                               ^
whatsapp-protocol.cc: At global scope:
whatsapp-protocol.cc:1139:12: warning: 'int isgroup(std::string)' defined but no
t used [-Wunused-function]
 static int isgroup(const std::string user)
            ^
i686-w64-mingw32-g++ -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra
-fPIC -DPURPLE_PLUGINS -DPIC -IC:/mingw32/pidgin/libpurple    -I "/pidgin/libpur
ple/" -I "/win32-dev/gtk_2_0-2.14/include/glib-2.0/" -I "/win32-dev/gtk_2_0-2.14
/lib/glib-2.0/include/" -o wa_api.o wa_api.cc
wa_api.cc:1:0: warning: -fPIC ignored for target (all code is position independe
nt)

 ^
i686-w64-mingw32-g++ -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra
-fPIC -DPURPLE_PLUGINS -DPIC -IC:/mingw32/pidgin/libpurple    -I "/pidgin/libpur
ple/" -I "/win32-dev/gtk_2_0-2.14/include/glib-2.0/" -I "/win32-dev/gtk_2_0-2.14
/lib/glib-2.0/include/" -o rc4.o rc4.cc
rc4.cc:1:0: warning: -fPIC ignored for target (all code is position independent)

 ^
i686-w64-mingw32-g++ -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra
-fPIC -DPURPLE_PLUGINS -DPIC -IC:/mingw32/pidgin/libpurple    -I "/pidgin/libpur
ple/" -I "/win32-dev/gtk_2_0-2.14/include/glib-2.0/" -I "/win32-dev/gtk_2_0-2.14
/lib/glib-2.0/include/" -o keygen.o keygen.cc
keygen.cc:1:0: warning: -fPIC ignored for target (all code is position independe
nt)

 ^
i686-w64-mingw32-g++ -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra
-fPIC -DPURPLE_PLUGINS -DPIC -IC:/mingw32/pidgin/libpurple    -I "/pidgin/libpur
ple/" -I "/win32-dev/gtk_2_0-2.14/include/glib-2.0/" -I "/win32-dev/gtk_2_0-2.14
/lib/glib-2.0/include/" -o tree.o tree.cc
tree.cc:1:0: warning: -fPIC ignored for target (all code is position independent
)

 ^
i686-w64-mingw32-g++ -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra
-fPIC -DPURPLE_PLUGINS -DPIC -IC:/mingw32/pidgin/libpurple    -I "/pidgin/libpur
ple/" -I "/win32-dev/gtk_2_0-2.14/include/glib-2.0/" -I "/win32-dev/gtk_2_0-2.14
/lib/glib-2.0/include/" -o databuffer.o databuffer.cc
databuffer.cc:1:0: warning: -fPIC ignored for target (all code is position indep
endent)

 ^
In file included from wa_connection.h:9:0,
                 from databuffer.cc:9:
wacommon.h: In function 'long long unsigned int str2lng(std::string)':
wacommon.h:16:31: warning: format '%u' expects argument of type 'unsigned int*',
 but argument 3 has type 'long long unsigned int*' [-Wformat=]
  sscanf(s.c_str(), "%I64u", &r);
                               ^
databuffer.cc: In member function 'DataBuffer* DataBuffer::decompressedBuffer()'
:
databuffer.cc:112:14: warning: comparison of unsigned expression >= 0 is always
true [-Wtype-limits]
  if (outsize >= 0)
              ^
In file included from wa_connection.h:9:0,
                 from databuffer.cc:9:
wacommon.h: At global scope:
wacommon.h:12:27: warning: 'long long unsigned int str2lng(std::string)' defined
 but not used [-Wunused-function]
 static unsigned long long str2lng(std::string s)
                           ^
wacommon.h:23:20: warning: 'std::string i2s(unsigned int)' defined but not used
[-Wunused-function]
 static std::string i2s(unsigned int num)
                    ^
wacommon.h:30:12: warning: 'int a2i(const string&)' defined but not used [-Wunus
ed-function]
 static int a2i(const std::string & s)
            ^
wacommon.h:37:15: warning: 'double str2dbl(std::string)' defined but not used [-
Wunused-function]
 static double str2dbl(std::string s)
               ^
wacommon.h:46:20: warning: 'std::string getusername(std::string)' defined but no
t used [-Wunused-function]
 static std::string getusername(std::string user)
                    ^
i686-w64-mingw32-g++ -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra
-fPIC -DPURPLE_PLUGINS -DPIC -IC:/mingw32/pidgin/libpurple    -I "/pidgin/libpur
ple/" -I "/win32-dev/gtk_2_0-2.14/include/glib-2.0/" -I "/win32-dev/gtk_2_0-2.14
/lib/glib-2.0/include/" -o message.o message.cc
message.cc:1:0: warning: -fPIC ignored for target (all code is position independ
ent)

 ^
In file included from message.cc:3:0:
wacommon.h: In function 'long long unsigned int str2lng(std::string)':
wacommon.h:16:31: warning: format '%u' expects argument of type 'unsigned int*',
 but argument 3 has type 'long long unsigned int*' [-Wformat=]
  sscanf(s.c_str(), "%I64u", &r);
                               ^
wacommon.h: At global scope:
wacommon.h:12:27: warning: 'long long unsigned int str2lng(std::string)' defined
 but not used [-Wunused-function]
 static unsigned long long str2lng(std::string s)
                           ^
wacommon.h:30:12: warning: 'int a2i(const string&)' defined but not used [-Wunus
ed-function]
 static int a2i(const std::string & s)
            ^
wacommon.h:37:15: warning: 'double str2dbl(std::string)' defined but not used [-
Wunused-function]
 static double str2dbl(std::string s)
               ^
i686-w64-mingw32-g++ -c -std=c++11 -Wno-unused-parameter -O2 -m32 -Wall -Wextra
-fPIC -DPURPLE_PLUGINS -DPIC -IC:/mingw32/pidgin/libpurple    -I "/pidgin/libpur
ple/" -I "/win32-dev/gtk_2_0-2.14/include/glib-2.0/" -I "/win32-dev/gtk_2_0-2.14
/lib/glib-2.0/include/" -o whatsapp_api.o whatsapp_api.cc
whatsapp_api.cc:1:0: warning: -fPIC ignored for target (all code is position ind
ependent)

 ^
In file included from wa_connection.h:9:0,
                 from whatsapp_api.cc:3:
wacommon.h: In function 'long long unsigned int str2lng(std::string)':
wacommon.h:16:31: warning: format '%u' expects argument of type 'unsigned int*',
 but argument 3 has type 'long long unsigned int*' [-Wformat=]
  sscanf(s.c_str(), "%I64u", &r);
                               ^
wacommon.h: At global scope:
wacommon.h:12:27: warning: 'long long unsigned int str2lng(std::string)' defined
 but not used [-Wunused-function]
 static unsigned long long str2lng(std::string s)
                           ^
wacommon.h:23:20: warning: 'std::string i2s(unsigned int)' defined but not used
[-Wunused-function]
 static std::string i2s(unsigned int num)
                    ^
wacommon.h:30:12: warning: 'int a2i(const string&)' defined but not used [-Wunus
ed-function]
 static int a2i(const std::string & s)
            ^
wacommon.h:37:15: warning: 'double str2dbl(std::string)' defined but not used [-
Wunused-function]
 static double str2dbl(std::string s)
               ^
wacommon.h:46:20: warning: 'std::string getusername(std::string)' defined but no
t used [-Wunused-function]
 static std::string getusername(std::string user)
                    ^
i686-w64-mingw32-g++ -shared  -o libwhatsapp.dll wa_purple.o tinfl.o imgutil.o w
hatsapp-protocol.o wa_api.o rc4.o keygen.o tree.o databuffer.o message.o whatsap
p_api.o libwhatsapp.res    -lfreeimage -L "/win32-dev/gtk_2_0-2.14/lib/" -L "/pi
dgin/libpurple/" -lglib-2.0 -lpurple -static-libgcc -static-libstdc++
strip --strip-debug --discard-locals libwhatsapp.dll

C:\whatsapp-purple-master>

**Comment by davidgfnet** [comment]
It's a pain to debug, but my guess is that you are missing FreeImage.dll, so pidgin cannot load the dll. Run pidgin as "pidgin --debug" it will give some extra info (although not much)

**Comment by G0Y0** [comment]
Get the library as follows:
1º http://freeimage.sourceforge.net/  ----> FreeImage.dll  -----> x32
2º C:\>pexports FreeImage.dll | sed "s/^_//" > libfreeimage.def
3º C:\>dlltool --add-underscore -d libfreeimage.def -l libfreeimage.a
4º C:\>mingw32\lib\libfreeimage.a
There is something wrong?

**Comment by davidgfnet** [comment]
That's a bit hacky, but probably works. I have no idea, I compiled libfreeimage myself and therefore got a .dll and a .dll.a file which I use to link.

**Comment by davidgfnet** [comment]
There are many issues discussing windows building. In this case I think it's just a dependency stuff, since it seems to build well. Use PE explorer or similar tool to track lib imports.
