### ISSUE TITLE
Whatsapp does not receive message or get delayed

### ISSUE THREAD

**Issue by thomaswpp** [davidgfnet/whatsapp-purple#261]
I've got a problem, my whatsapp gets message late or does not receive the message, I can see the person writing the message but not enough. My pc is xubuntu 32 bits. whatsapp-purple 0.81, info:

Serves: c2.whatsapp.net
Port: 443
Resurce: Android-2.31.151-443

**Comment by JayFoxRox** [comment]
Confirmed with version 0.7 on 64 bit Arch.

Server: c2.whatsapp.net
Port: 443
Resource: WP7-2.11.596-443

I have now upgraded to the current git version, I'll keep my WP7 resource but might change it to "Android-2.12.5-443" soon which seems to be the plugin default if the problem isn't solved [as the original issue suggests the problem still exists in 0.8.1 / git version].

You can confirm this issue for yourself by messaging yourself.
I believe I had this issue before [a couple of months ago] and fixed it by changing my resource. It was gone for a long time and the problems (probably) came back on Saturday (April 2nd). It happens from time to time but sometimes silently goes away.

**Comment by angelbladex** [comment]
Same story with recent version on 32 bits Arch

**Comment by salvattore001** [comment]
same here

**Comment by davidgfnet** [comment]
Can you check with a fresh (100% fresh, no user data, no config...)
installation?
To be more specific: delete ~/.purple, delete any .so/.dll and build git
HEAD.
That would be awesome. Reporting errors in PPA versions or version 0.7 with
some old config doesnt really helps, actually it has a negative helpful
factor.
