### ISSUE TITLE
Disconnect/reconnect problem

### ISSUE THREAD

**Issue by eduardmartinez** [davidgfnet/whatsapp-purple#263]
Hi. Since last Friday, my whatsapp account is disconnecting and reconnecting (sometimes I have to reconnect manually). Before last Friday, all was working perfectly. What could be the reason for this behavior?

**Comment by ps2reality** [comment]
Hello. I have the same problem.

**Comment by pabloscasas** [comment]
The same problem here. At some periods of time, the problem seems to be fixed by itself.

**Comment by davidgfnet** [comment]
I think most of the problems are because you guys are using an old version. I fixed this issue in recent commits...
But I guess it's easier to complain than to update :P

**Comment by eduardmartinez** [comment]
Hehe, I'm sorry man. I haven't made a update since 2 months ago. I'll do it and I'll tell you. I wasn't complaining just made a question :P

**Comment by davidgfnet** [comment]
Understood, but you should understand that I get bucketloads of emails
every day.
There is also similar issues, so please use the search button before
creating a new issue.

**Comment by eduardmartinez** [comment]
It seems the update fixed the problem. I'm sorry again but I searched in issues and I didn't see what was happening to me. Anyway, thanks for your time and your answer and for this great plugin.

**Comment by caccamo88** [comment]
hi guys
please help me, same problem "my whatsapp account is disconnecting and reconnecting (sometimes I have to reconnect manually)" have not understand what I should update and how :( can someone kindly explain?
Regards

**Comment by pabloscasas** [comment]
A possible solution is updating the plugin to the last version.

**Comment by caccamo88** [comment]
can't follow me step by step? Thanks

**Comment by axel21a** [comment]
If you use windows get the latest version already compiled david, the "whatsapp4pidgin-0.8.2"
works beautifully, you just have to make a small contribution, but it seems the minimum for an excellent job well
https://gosell.it/product/whatsapp-for-pidgin-20

**Comment by caccamo88** [comment]
thanks for reply: have purchased the plugin but not solve at all my problem :( (randomly disconnet me and most important all messages sent during disconnection are lost forever, not come when reconnected)
What I have done: purchased the plugin, double click install, then enable the plugin from pidgin tools-->plugin (ticked whatsapp pldgin plugin)

**Comment by axel21a** [comment]
is weird, I'm using now works perfectly.but the resource settings are correct?maybe it's time that placed one shot settings 



     Il Lunedì 18 Maggio 2015 12:50, caccamo88 <notifications@github.com> ha scritto:
   

 thanks for reply: have purchased the plugin but not solve at all my problem :( (randomly disconnet me and most important all messages sent during disconnection are lost forever, not come when reconnected)
What I have done: purchased the plugin, double click install, then enable the plugin from pidgin tools-->plugin (ticked whatsapp pldgin plugin)—

**Comment by caccamo88** [comment]
server: c2.whatsapp.net
port: 443
Resource: Android-2.31.151-443

**Comment by caccamo88** [comment]
perhaps have solved! have deleted manually all previous trace of the plugin 
(basically have deleted the file "last-whatsapp.dll" was inside %Programfiles%\Pidgin\plugins )
And then let install all automatically by click the the 0.8.2.exe package just purchased.
Can't say "victory" but no disconnects in the last 10 minutes and almost all (that is the thing make me thing problem perhaps solved) I see the whatsapp "tick" (message sent, arrived, read) that me never saw before

**Comment by caccamo88** [comment]
update: disconnections seems not occurs no more BUT now seems I am not able to receive messages from certain contacts have not understood the criteria :(

**Comment by davidgfnet** [comment]
Again, if you don't receive messages form some contacts, check whether they have android phones. In that case ask for a new password. That happens because of the end to end android encryption.

**Comment by caccamo88** [comment]
hi davidgfnet thanks for reply. Your plugin solved the disconnections problem but now have the message not arriving problems. Have asked new password several times with no solution :( Any other hint? (me have asked with wart WART-1.8.2.0.exe the other previous versions returns me "old_version"
Regards

**Comment by jasmine758** [comment]
@davidgfnet I tried with a new password as well, but I am still not able to receive messages from some contacts. Any more hints?
