### ISSUE TITLE
new password

### ISSUE THREAD

**Issue by axel21a** [davidgfnet/whatsapp-purple#264]
How do I get my password? 
wart is no longer.
I had to renew my subscription to whatsapp, they have sent a text message with the new code, but if you use wart 1.7.3 gives me this error:
can anyone help me?
![image](https://cloud.githubusercontent.com/assets/9769377/7543511/3691b96e-f5c5-11e4-86fe-2501519392c4.png)

**Comment by davidgfnet** [comment]
reason: old_version
Use WART 1.8+

**Comment by axel21a** [comment]
thanks david, in fact I was able to find wart 1.8.1 - but it seems that the author is no longer the same.
still all right
