### ISSUE TITLE
Pidgin aborts when connecting to whatsapp server

### ISSUE THREAD

**Issue by pabloscasas** [davidgfnet/whatsapp-purple#266]
As commented in https://github.com/davidgfnet/whatsapp-purple/issues/254#issuecomment-99664011 since version 0.8.1 included, Pidgin is not able to connect to whatsapp server and aborts inmediately. I use Pidgin 2.10.10 from gentoo x86_64.

In spite of our "complains" or bugs in the plugin, we are very grateful to your work, davidgfnet.

**Comment by the98** [comment]
You're probably blocked. Same happened to me.

**Comment by pabloscasas** [comment]
I am not blocked because I connect with previous versions.

**Comment by dequis** [comment]
Quoting from the linked comment:

> ```
(19:36:17) dns: Got response for 'c2.whatsapp.net'
(19:36:17) dnsquery: IP resolved for c2.whatsapp.net
(19:36:17) proxy: Attempting connection to 173.192.222.170
(19:36:17) proxy: Connecting to c2.whatsapp.net:443 with no proxy
(19:36:17) proxy: Connection in progress
Pidgin 2.10.10 ha tenido un fallo y ha intentado generar un archivo «core».
Esto es una errata en el programa y no se ha producido por
algo que haya hecho.

> Si puede reproducir este fallo, por favor, notifíquelo a los
desarrolladores de Pidgin enviando un informe de errata a
http://developer.pidgin.im/simpleticket/

> Asegúrese de especificar lo que estaba haciendo en el momento de
suceder esto y envíenos su traza del archivo «core». Si no sabe como
obtener una traza consulte las instrucciones disponibles en
http://developer.pidgin.im/wiki/GetABacktrace
dns[16274]: Oops, father has gone, wait for me, wait...!
Abortado
```

So, do what https://developer.pidgin.im/wiki/GetABacktrace says

**Comment by pabloscasas** [comment]
I obtain the following extra information from gdb. I hope it helps.

Program received signal SIGABRT, Aborted.
0x00007ffff4972e77 in raise () from /lib64/libc.so.6
(gdb) #0  0x00007ffff4972e77 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff497427a in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff49b0d74 in ?? () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff49b61ae in ?? () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007ffff49ba3ca in realloc () from /lib64/libc.so.6
No symbol table info available.
#5  0x00007fffecccf8f1 in DataBuffer::addData(void const*, int) ()
   from /home/jpablo/.purple/plugins/libwhatsapp.so
No symbol table info available.
#6  0x00007fffeccc3f15 in WhatsappConnection::receiveCallback(char const*, int) () from /home/jpablo/.purple/plugins/libwhatsapp.so
No symbol table info available.
#7  0x00007fffeccaac55 in waprpl_input_cb ()
   from /home/jpablo/.purple/plugins/libwhatsapp.so
No symbol table info available.
#8  0x0000000000468b0e in ?? ()
No symbol table info available.
#9  0x00007ffff523a925 in g_main_context_dispatch ()
   from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#10 0x00007ffff523ac88 in ?? () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#11 0x00007ffff523af4a in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
No symbol table info available.
#12 0x00007ffff6d66227 in gtk_main () from /usr/lib64/libgtk-x11-2.0.so.0
No symbol table info available.
#13 0x0000000000431b3e in main ()
No symbol table info available.
(gdb)

**Comment by pabloscasas** [comment]
It seems  that with the latest version of the plugin (0.8.2-8-g948484a) Pidgin doesn't abort anymore, so the problem is fixed. Thank you for the good work.
