### ISSUE TITLE
Debug outputs unescaped binary characters to console

### ISSUE THREAD

**Issue by dequis** [davidgfnet/whatsapp-purple#270]
And most of the time I can't see shit

The Data part of `Tree::toString` in particular.

The one that makes most sense is `Data: �JFIF ...`.

I'd shove [g_strescape][1] in there but not sure if you're okay with using glib functions from the c++ part of the code. I also wanted to try adding that to the purple side only, but apparently you're throwing these messages directly to stdout, not going through purple_debug_whatever, so idklol. [Copypasting shit from stackoverflow][2] could also work.

[1]: https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-strescape
[2]: http://stackoverflow.com/a/2417770/2195033

**Comment by davidgfnet** [comment]
Yeah right... I should probably scape that. Do you consider it important? I mean, throwing binry data is not a big deal isn't it?

**Comment by dequis** [comment]
Not *very* important (other than the small possibility of printing one of those escape codes that break the rendering of the rest of the terminal), but outputting that isn't very useful if it's all stuff that just appears as �. Although it's just the first chars 10 chars so maybe even after escaping it wouldn't be very useful either. Do you actually use this output for debugging?

I just see these things and "Data" has a suspicious space there which could be anything:

```
Tag: iq
at[from]=g.us
at[id]=3
at[type]=error
Data:  ...
 Tag: error
 at[code]=500
 at[text]=internal-server-error
 Data:  ...
```

This one seems to be harmless though. The first issue i wanted to debug was some server side disconnection that just fixed itself after upgrading to the latest git version, so all i've got left to complain about is the debug output :D

**Comment by davidgfnet** [comment]
Haha ok.
Well I use it quite often. JPEG header is recognizable and helps debugging but yeah.
