### ISSUE TITLE
Pidgin doesn't see libwhatsapp.so

### ISSUE THREAD

**Issue by haunted2** [davidgfnet/whatsapp-purple#272]
Hello, i compiled whatsapp-purple on debian jessie with pidgin-2.10.11. All went fine, but after copying libwhatsapp.so in ~/.purple/plugins (or even in /usr/lib/purple-2) and restarting pidgin, whatsapp is not listed between protocols in account creation.
Starting pidgin in terminal shows no errors.

Any hint? Thanks..

**Comment by davidgfnet** [comment]
Probably missing some dependencies?

**Comment by haunted2** [comment]
It seems that was because of the facebook (XMPP) chat account, after deleting that one, pidgin was able to create the whatsapp account and everything work. The issue can be closed, thanks.
