### ISSUE TITLE
Your phone number +XX XXX XXX XXXX is no longer allowed to use our service.

### ISSUE THREAD

**Issue by masavini** [davidgfnet/whatsapp-purple#275]
hi,
i've been successfully using this library over the last year.

this morning i could not connect anymore. i tried and open whatsapp on my phone, and i got the subject message.

so i found this: http://www.whatsapp.com/faq/en/general/23154266

i obviously did not offend anyone with my chats (i mostly use it to chat with my wife, who stays downstairs :)) , so i guess the suspension is due to using an unofficial client.

any hint to solve this?
thanks...

**Comment by githubtefo** [comment]
Same for me. Since this morning too.
I wrote an email to support@whatsapp.com requesting the account re-activation. I think it's the only thing we can do. We'll see what they say...
Could we do some kind of demand using any consumer rights organization? I mean, ok, we are violating the ToS by using a protocol (an open source protocol? https://www.whatsapp.com/opensource/) as we wish to. But they are blocking our freedom to communicate us with people.

**Comment by dequis** [comment]
>Could we do some kind of demand using any consumer rights organization?

lol

**Comment by CrimsonGlory** [comment]
I can't connect anymore. A few hours ago it worked. Maybe they banned us all.

(23:48:45) account: Connecting to account XXXXXXXXXXXXX.
(23:48:45) connection: Connecting. gc = 0x7fd9d1fd2ee1
(23:48:45) whatsapp: logging in XXXXXXXXXXXXX
(23:48:45) dnsquery: Performing DNS lookup for c2.whatsapp.net
(23:48:45) dns: Wait for DNS child 16359 failed: No child processes
(23:48:45) dns: Created new DNS child 16993, there are now 1 children.
(23:48:45) dns: Successfully sent DNS request to child 16993
(23:48:45) dns: Got response for 'c2.whatsapp.net'
(23:48:45) dnsquery: IP resolved for c2.whatsapp.net
(23:48:45) proxy: Attempting connection to 173.192.222.169
(23:48:45) proxy: Connecting to c2.whatsapp.net:443 with no proxy
(23:48:45) proxy: Connection in progress
(23:48:45) proxy: Connecting to c2.whatsapp.net:443.
(23:48:45) proxy: Connected to c2.whatsapp.net:443.
(23:48:48) connection: Connection error on 0x7fd9d1fd2ee1 (reason: 2 description: not-authorized)
(23:48:48) account: Disconnecting account XXXXXXXXXXXXX (0x7fd9d1515a19)
(23:48:48) connection: Disconnecting connection 0x7fd9d1fd2ee1
(23:48:48) connection: Destroying connection 0x7fd9d1fd2ee1
(23:48:51) util: Writing file accounts.xml to directory /home/user/.purple
(23:48:51) util: Writing file /home/user/.purple/accounts.xml

**Comment by dequis** [comment]
See #224 for the catch-all ticket for bans and stuff.

@CrimsonGlory Re-register that number. If it says you're blocked, you're blocked, if not, you'll get a new password

**Comment by erickc55** [comment]
githubtefo,

did they answer your email?

Your account was reactivated?

**Comment by masavini** [comment]
i've been reactivated yesterday: they asked for a screenshot of the official application installed and anfter a few minutes i was connected again.
they also said that if i'm caught again on an unofficial client i'll be banned forever...

**Comment by davidgfnet** [comment]
BTW how did you fake the original client's screenshot? I'm curious :D

**Comment by masavini** [comment]
i did not fake anything: i really installed whatsapp on my mobile and inserted the sim...

**Comment by githubtefo** [comment]
I'm currently installing the android sdk right now to do it.
I'll tell you the results.
It's ridiculous.

**Comment by davidgfnet** [comment]
What do you exactly need? Maybe we can send an screenshot to you...
@masavini can you send me your screenshot by email? I've got a genious idea

**Comment by githubtefo** [comment]
I don't know what I need exactly.
The person from support@whatsapp.com wrote me that I should send them "a screenshot of the verification process step which contains the cellphone number that I activated with Whatsapp".
I can emulate android sdk, but I lost 1 hour trying to understand how to install Whatsapp on this SO (some issues with my gmail and the play store bla bla bla).
@davidgfnet, are you thinking on create an app with the screenshot and any cellphone number? :)
I should go back to my real work.

**Comment by davidgfnet** [comment]
:D Yeah something like that. Let's just fake it.
You can get the whatsapp apk at their website, no need to use the bloody
play store.

**Comment by githubtefo** [comment]
I sent three days ago this (I put the same name than an android's screenshot of a friend of mine):

![screenshot_2015-06-08-12-30-56](https://cloud.githubusercontent.com/assets/11220103/8097558/131c1e02-0fba-11e5-9032-b49df97d00e8.png)

And now they reactivate my account (they also said that if i'm caught again on an unofficial client i'll be banned forever).
May be if we only change with GIMP the numbers in the image they believe us...
Tomorrow I can send you guys another image with "123456790" so you can reorder the numbers.
Something else: What should I do for not being banned again? Can I use the 0.8.1 version in Ubuntu (for some reason the official PPA doesnt update the package to the last version on 12.04 LTS) and the 0.8.2 in arch? And which Resource should I use? Should be the same in both OS?
Thanks!

**Comment by davidgfnet** [comment]
Always use latest version. If you use an older one, stuff breaks. That is
why I release versions, because they fix things.

**Comment by masavini** [comment]
my 2 cents...

this is what i got from whatsapp support:
> It appears that you are using an unauthorized application of WhatsApp. Unauthorized applications are not supported; they contain source code which WhatsApp can not guarantee as safe. Your private information is potentially being passed to 3rd parties. In addition, these may not function correctly and may cease to work at any given time.

why don't you just contact them and say: "hi, my app is open source. no risk of malicious code nor privacy issues. would you please allow the users of my app not being banned?"

**Comment by davidgfnet** [comment]
And then I'll probably get a lawsuit, as manu other people already got.
I guess they haven't had the time but I'm probably going to get one too...
This is FB we are talking about guys, it's a money making company :(

**Comment by masavini** [comment]
how could you be a problem for their business? i mean, your users must be registered on whatsapp and pay whatsapp subscription. there are no ads on whatsapp, so there is no missing earning...

**Comment by dequis** [comment]
>why don't you just contact them and say: "hi, my app is open source. no risk of malicious code nor privacy issues. would you please allow the users of my app not being banned?"

Have *you* tried telling them that? Except the "my" parts, of course. (sure, that would be replying to a canned response, but hey, you're already in contact with them so whatever. good luck)

>how could you be a problem for their business? i mean, your users must be registered on whatsapp and pay whatsapp subscription. there are no ads on whatsapp, so there is no missing earning...

That's not something you should ask here, I mean, from our point of view they are just being dicks for no good reason. They probably do have a reason but we don't know it.

**Comment by githubtefo** [comment]
Again im out (Not-authorized response). I could reactivate my account with yowsup-cli registration. Instead of obtaining a sms-code I directly had a new password. But when I introduce it I still can not connect to the server.
Any ideas? (Ubuntu 12.04, v0.8.4).

**Comment by Raaff** [comment]
@githubtefo I've got exactly the same problem. First pidgin gave the "not authorized" error, then I got a new password with yowsup-cli (without an sms), then whatsapp-purple still wouldn't work (without the "not authorized" part, but with a timeout in the end). Strange thing is I'm able to use my whatsapp account through yowsup-cli (sending and receiving messages works there). Both whatsapp-purple and yowsup are freshly build.

**Comment by masavini** [comment]
sorry to tell you, folks... but it really seems that the way to use whatsapp on pc is with they're official web client (web.whatsapp.com). and i must admit it works pretty good!

**Comment by davidgfnet** [comment]
Hey guys, it does work for me. I use this:
Server: 173.192.222.177
Port: 443
Resource: Android-2.12.5-443

**Comment by davidgfnet** [comment]
Current whatsapp android version is 2.12.176, maybe worth trying. Yowsup is using S40 that is probably the reason why it does work.
In my case I used two accounts (US & UK) and it does work...

**Comment by githubtefo** [comment]
@davidgfnet , @Raaff 
Server: 173.192.222.177
Port: 443
Resource: Android-2.12.176

Works for me! With the last password that yowsup-cli gave me.
@masavini , the official web client is not an alternative to me, because i'm using Firefox OS on my cell phone and I don't have the official client there either.
The best solution for me at the moment is using my PC with whatsapp-purple in pidgin and resend all the messages via a xmpp account to my phone.

**Comment by davidgfnet** [comment]
@githubtefo How do you do that? There is something called spectrum2 but doesn't work out of the box really.

**Comment by githubtefo** [comment]
@davidgfnet I can receive messages from my pidgin accounts (gtalk, whatsapp-purple) to my xmpp account on my cell phone using the pidgin plugin forward2mobile (https://code.google.com/p/forward2mobile/). Unfortunately, the command to send messages from the mobile to anyone in the buddy list is not working in my case.

**Comment by Raaff** [comment]
@githubtefo that didn't work for me, but when I changed the port to 5222 it finally did! I'm happy again.

BTW, if you want to get messages on multiple devices, you can put your .purple directory in a cloud (private cloud of course ;) like seafile ). That way you have chats on multiple devices, but it is not "suspicious" as the resource-string is the same.

**Comment by davidgfnet** [comment]
I guess we can close this one...

**Comment by mickronson205** [comment]
Payroll Accounting is the most important and critical aspect of the business management process. Also, if you need technical assistance for your QuickBooks payroll software by experts, connect with us at [](https://www.lawyercontactnumber.com/quickbooks-payroll-support-phone-number/) QuickBooks Payroll Support Phone Number @ +1-888-744-6OO5. It is true that precise and well-organized bookkeeping plays a very important role in your business growth.

**Comment by richardscarry56** [comment]
For any technical assistance related to QuickBooks, call now at [QuickBooks Technical Support Phone Number](https://www.dialqb.com/quickbooks-technical-support-phone-number/) @ 1-8OO-213-9768. We are available 24x7 for you. QuickBooks is versatile and customized software that imparts flexibility in business accounting features. Contact the tech support providers at [QuickBooks Technical Support Phone Number](https://tinyurl.com/svk7o2u) @ 1-8OO-213-9768. For answers regarding QuickBooks issues. This assistance is constant for the users throughout the technically difficult phase.
Read more: [https://rb.gy/aubeub](https://rb.gy/aubeub)
[https://cutt.ly/urR9XTl](https://cutt.ly/urR9XTl)
[https://bit.do/fqMaD](https://bit.do/fqMaD)

**Comment by mickronson205** [comment]
I don't know what I need exactly.
The person from support@[whatsapp.com](https://www.lawyercontactnumber.com/quickbooks-payroll-support-phone-number/) wrote me that I should send them "a screenshot of the verification process step which contains the cellphone number that I activated with [Whatsapp](https://tinyurl.com/y3jokcta)".
I can emulate android sdk, but I lost 1 hour trying to understand how to install [Whatsapp](http://tiny.cc/baptfz) on this SO (some issues with my gmail and the play store bla bla bla).
@[davidgfnet](http://bit.do/fgcoF), are you thinking on create an app with the screenshot and any cellphone [number](https://cutt.ly/leTmmCB)? :)
I should go back to my real work.

**Comment by madonaamax** [comment]
QuickBooks is #1 accounting software which is used for small and mid-size businesses to perform accounting functions. To get immediate assistance from our support team, call us on [QuickBooks Support Phone Number](https://www.dialqb.com/quickbooks-support-phone-number/) @ 1-8OO-213-9768. It’s reliable, supportive, and easy to use features has contributed a lot towards its popularity. Almost ninety-eight percent of its users believe that QuickBooks is the most straightforward accounting software. This software is so trending that it is trusted and used by more than 4.2 million people.
Read more: [https://tinyurl.com/qomcl3z](https://tinyurl.com/qomcl3z)
[https://rb.gy/gbyhuq ](https://rb.gy/gbyhuq )
[https://cutt.ly/1tqOiV5](https://cutt.ly/1tqOiV5)
[http://bit.do/fxF82](http://bit.do/fxF82)

**Comment by JohnMocus** [comment]
Same for me. Since this morning too.
I wrote an email to [support@whatsapp.com](https://rb.gy/wpcfvu) requesting the account re-activation. I think it's the only thing we can do. We'll see what they say...
Could we do some kind of demand using any consumer rights organization? I mean, ok, we are violating the ToS by using a protocol (an open source protocol?([www.whatsapp.com/](https://www.colposol.com/)[opensource] as we wish to. But they are blocking our freedom to communicate us with people.

**Comment by evamendes67** [comment]
QuickBooks is the modern-day tool to get rid of the daily basis accounting problems. Contact us at QuickBooks Support Phone Numberfor seamless doorstep services. We ensure the complete removal of the problems faced by the users as soon as possible. Get in touch with us and see all your problems disappearing. Our assisting and responsible executives are 24*7 contactable and interrogable. Feel free to ring us and access our website for quick resolutions. 

Visit here:-https://www.acctphonenumber.tech

**Comment by evamendes67** [comment]
QuickBooks has been the life-saver and the medium to enhance productivity associated with many modern businesses. You can share your working experience with us at QuickBooks Enterprise Support Number. 
Visit here;-https://www.qaenterprisesolved.online

**Comment by bh1096774-dot** [comment]
Xxxx Sister and brother
