### ISSUE TITLE
Buddy status (online, away etc) not updated in pidgin

### ISSUE THREAD

**Issue by jasmine758** [davidgfnet/whatsapp-purple#278]
I went through the different issues reported and couldn't find anything related to what I am facing. What is happening is once I login to WhatsApp using pidgin, the plugin works just fine. However the status for buddies does not update once logged in. It stays as it is even though it has changed. I could see the issue as I have 2 WhatsApp accounts for two different numbers. When I go offline from moblie, in pidgin it shows as online. I am not sure whether WhatsApp server stopped sending the presence information. A few days back it was working fine.

Any help would be appreciated

**Comment by davidgfnet** [comment]
It works well for me, no idea what it could be. There is some delay in the updates though

**Comment by jasmine758** [comment]
For me the buddy status does not update after logging in. Lets see if some one else is also facing this issue. Is there any specific WhatsApp server you are trying to connect to? Here is my configuration

server - c1.whatsapp.net
port - 443
resource - WP7-2.11.596-443

**Comment by jasmine758** [comment]
Now the buddy status is updated as expected. What I had done was I had explicitly set my status as Away which i think disabled the buddy status update. Once I set my status to Available, the buddy status started reflecting. I guess my Away status was causing the issue.

**Comment by davidgfnet** [comment]
Yes, when you are Away you don't receive any update (your phone is
supposed to be sleeping, so there is no point on getting updates!)

Please close the issue.
David
