### ISSUE TITLE
Sort the privilegies on group

### ISSUE THREAD

**Issue by angelbladex** [davidgfnet/whatsapp-purple#281]
Hi!
On recent updates, i see on one group these symbols

![a](https://cloud.githubusercontent.com/assets/847922/8139803/4629f276-1120-11e5-8304-efe33ec78232.jpg)

The star is a owner o creator o main admin and the flag is a co-admin. If a admin/creator of group have high privilegies, the order is wrong on this case.

**Comment by davidgfnet** [comment]
Nope. Flag is owner (and obviously admin) and stars are admin.
The order doesnt really matter.

**Comment by davidgfnet** [comment]
So what was the issue then? I did not get it sorry

**Comment by angelbladex** [comment]
On all my groups, the main admin have a star, one group have co-admin and co-admin apparear first on list (check image)
