### ISSUE TITLE
Connecting to a whatsapp group denied

### ISSUE THREAD

**Issue by Imhotep-2700bc** [davidgfnet/whatsapp-purple#284]
Hello,
since yesterday I'm blocked connecting to a whatsapp group. The chat group manager tried to renew my membership but got a message that I should update my WhatsApp app. That's strange because person to person chats works fine. To me it seems to be a special problem with group chats.
Current package on openSuse Linux: libpurple-plugin-whatsapp-0.7-1.1.x86_64
Current Pidgin resource: WP7-2.11.596-443

**Comment by jlguardi** [comment]
I was using group chats with yowsup but I can't use now due to w:g protocol is not supported anymore. However, I've ported all protocol to w:g2 and I can use all functionality. 
As far as I know, purple uses w:g2 but pehaps some function is still with old protocol.

**Comment by jlguardi** [comment]
Please, forget my comment. Purple uses w:g2 in all group Iqs.

**Comment by arccosh** [comment]
I think I have the same issue, because I lost my WhatsApp groups since yesterday. And now I get sometimes the following message:
"Invitation only
Joining (null) requires an invitation."
I think this message occurs when someone post something in this group. Maybe this helps to fix it.

**Comment by Imhotep-2700bc** [comment]
[arccosh]: "I think this message occurs when someone post something in this group."

Good hint. While during many hours nothing happens, I wondered that I got 5 such messages in a short time.

**Comment by Imhotep-2700bc** [comment]
Hello,
I compiled and run the latest version 0.8.2 of whatsapp-puple. The problem still exists.

**Comment by Imhotep-2700bc** [comment]
Ups, sorry, clicked the wrong button.

**Comment by Imhotep-2700bc** [comment]
Interesting detail. 
Since the update to version 0.8.2 I receive messages from my whatsapp group. But the group isn't named, whatsapp-purple tells it "unknown".
When I try to join the group I still get the message "Invitation only ....."

**Comment by davidgfnet** [comment]
Anybody tried HEAD? There are some w:g2 updates. 0.8.2 still uses old groups.

Thanks

**Comment by Imhotep-2700bc** [comment]
I don't understand what you mean with HEAD, the current master version?
Well, I compiled the new master version. Problem is solved.
Thanks

**Comment by davidgfnet** [comment]
Yes that is what I meant, so the current master is working but 0.8.2 does not work.
Then I guess the problem is solved. PLEASE: Never report bugs in older versions, since that confuses people and makes no sense to report "old" bugs that have been fixed.
Thanks
