### ISSUE TITLE
Wrong info on the whatsapp-purple website for non-developers

### ISSUE THREAD

**Issue by Faiz7412** [davidgfnet/whatsapp-purple#285]
I was unable to build it from source.
Here's what happens when I run make: 

```
faiz@FZ:~/Downloads/whatsapp-purple-master$ make
gcc -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/local/include/libpurple -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -o imgutil.o imgutil.c
imgutil.c:2:23: fatal error: FreeImage.h: No such file or directory
 #include <FreeImage.h>
                       ^
compilation terminated.
make: *** [imgutil.o] Error 1
faiz@FZ:~/Downloads/whatsapp-purple-master$ 
```
despite several tries to resolve the issue, i wasn't able to build it. 
So I went over to the project's [website](https://davidgf.net/whatsapp/) , added ppa to my list. did apt-get update. 
and when I did `sudo apt-get install whatsapp-purple` , as stated on the website, I got this: `E: Unable to locate package whatsapp-purple`

replace 'sudo apt-get install whatsapp-purple' with 'sudo apt-get install pigdin-whatsapp'

**Comment by Imhotep-2700bc** [comment]
After adding the source code package of "freeimage" I was able to compile the source. I got it from the repository of my operating system.

**Comment by davidgfnet** [comment]
Is this solved?
Check the dependencies before building!

**Comment by Faiz7412** [comment]
I installed it using `sudo apt-get whatsapp-purple` 
However, WhatsApp protocol didn't show up in pidgin even after that. 
I tried building lots of times before but it failed. I'd attempt resolving the issues if I'm sure WhatsApp doesn't block its users who don't use their own official app. Or you can close this issue.

**Comment by Smile4ever** [comment]
Please add freeimage as a requirement to the README.

**Comment by AyushBhat** [comment]
how to get the FreeImage.h on Windows?
