### ISSUE TITLE
Windows Compilation Error

### ISSUE THREAD

**Issue by ghost** [davidgfnet/whatsapp-purple#286]
-------------- Build: Debug in whatsappdll (compiler: GNU GCC Compiler)---------------

Running command: make.exe -f Makefile.mingw Debug
Execution of 'make.exe -f Makefile.mingw Debug' in 'C:\Users\inventum\Desktop\lib\whatsappdll' failed.
Nothing to be done (all items are up-to-date).

**Comment by davidgfnet** [comment]
This is not a proper bug report. You are using some random IDE/Environment and expect me to come up with a magic solution? :D
