### ISSUE TITLE
Profile picture working

### ISSUE THREAD

**Issue by rybarczykbr** [davidgfnet/whatsapp-purple#287]
I don't know why, but the server accepted my profile picture.

I just choose a picture by clicking on the little button at the lower right corner of the contacts list, then went to "edit account" and checked "use this icon....".

Don't know what happened. Did you patch something, David?

**Comment by Imhotep-2700bc** [comment]
I think this extract of change log will answer your question:

> pidgin-whatsapp (0.8) trusty; urgency=low
>
>  * Ability to change profile picture
>  * Ability to set privacy options
>  * Fixed image sending by creating realistic thumbnails
>  * Fixed profile picture update for contacts in buddy list
>  * Fixing some features to look like an android phone
>  * Supports receiving broadcast messages
>  * Fixed some minor bugs with groups and some cleanup
>  * Fixed some leaks (probably some still ther)
>  * Fixing status message setting
>  * Fixed photo thumbnails display when receiving media messages
>
> -- David Guillen Fandos <david@davidgf.net>  Sun, 22 Mar 2015 23:23:00 +0100

**Comment by rybarczykbr** [comment]
Even with 0.8 version all I was getting was a blank (black) picture. Maybe the size of the jpg was too small.

Thanks again for this excellent plugin.
