### ISSUE TITLE
[Mejora] Habilitar Emoticonos de Whatsapp ([Enhancement] Enable Emoticons for Whatsapp)

### ISSUE THREAD

**Issue by Jeronimo17** [davidgfnet/whatsapp-purple#29]
Modificando el archivo <b>C:\Archivos de programa\Pidgin\pixmaps\pidgin\emotes\default\theme</b> y añadiendo manualmente cada icono.png (usando los de <b>Wassapp</b>) con su codigo unicode correspondiente.

---

[WhatsApp]
../whatsapp/E102.png  
../whatsapp/E103.png 
../whatsapp/E104.png 
../whatsapp/E105.png 
../whatsapp/E106.png 
../whatsapp/E107.png
../whatsapp/E108.png 
../whatsapp/E109.png 
../whatsapp/E10A.png 
../whatsapp/E10B.png 
../whatsapp/E10C.png 
../whatsapp/E10D.png 
../whatsapp/E10E.png 
../whatsapp/E10F.png 
../whatsapp/E110.png 
../whatsapp/E111.png
../whatsapp/E112.png 
../whatsapp/E113.png
../whatsapp/E114.png 

---

(He probado con estos y funcionan :D, los que faltan por poner el unicode dan error fatal en windows, cerrando pidgin al darle al icono de emoticonos; Se puede seguir añadiendo pero de cada cuatro, uno da error...)

![emoti](https://f.cloud.github.com/assets/4985763/1145952/507542ca-1e39-11e3-892e-f723ee9d6d9a.PNG)

A ver si lo pongo en la web oficial de Pidgin y lo arreglan...

Podría terminar esta lista si quieres cuando arreglen el problema y subírtela :)
Saludos

**Comment by programacion-web** [comment]
creo que le falta un scroll a la ventana de emoticons porque no me deja ver todos solo los primeros
