### ISSUE TITLE
Pidgin gives memory access violation while connecting, possibly due to umlaut (diéresis)

### ISSUE THREAD

**Issue by scheunengeist** [davidgfnet/whatsapp-purple#290]
Hey there!
As of late, Pidgin (2.10.11) is crashing during the attempt to get connected. This seems to be caused by the whatsapp-purple plugin, as Pidgin runs well when disabled.

I re-built Pidgin 2.10.11 from source with debuging enabled. I'm posting a few suspicious message lines:
```
(20:39:53) whatsapp: Opening conversation window for XXXX
(20:39:53) whatsapp: joining group N�ller
(20:39:53) gtkconv: setting active conversation on toolbar 0xa2487e8
(20:39:53) gtkconv: setting active conversation on toolbar 0xa2487e8
(20:39:53) prefs: /pidgin/conversations/toolbar/wide changed, scheduling save.
(20:39:53) log: Failed to open log file "/home/user/.purple/logs/na?ller.log" for reading: No such file or directory
(20:39:53) whatsapp: group info ID(XXXX) SUBJECT(Unknown) OWNER(000000)
Hi, user.  We need to talk.
I think something's gone wrong here.  It's probably my fault.
```

There are no log files whatsoever under ~/.purple/logs/, only a couple directories for the different services I use (e. g. whatsapp/ and jabber/).

Also, there's a special character (ä) in the group it's trying to join.

I've been successfully using a build from 2015-05-15 which worked fine. The next time I built the plugin (2015-06-06 iirc) it started crashing while connecting. A build from git marker 4a9ab575f1897 (recent as of June 25) also crashes.

I'm not a programmer, so my options for further analysis are limited. Please let me know if you need more information.

Thanks in advance!

**Comment by davidgfnet** [comment]
Hey scheunengeist, since I cannot reproduce the error myself (but I'm 100% sure there is something wrong there) can you help me debugging this?
Do a "make debug" instead of the regular "make". In fact, make sure to do a "make clean" and then a "make debug" and then install it and run piding. I would need a backtrace, that can be obtained using:

    gdb pidgin

Once it crashes do a "bt" in the gdb console to get a backtrace. That would help a lot!

**Comment by davidgfnet** [comment]
I just commited a small fix which might fix it. Can you rebuild with version 3f0370b and give it a try?
Thanks a lot!

**Comment by scheunengeist** [comment]
Hey, it seems you nailed it! I've built from version 3f0370b and connecting works fine.
Thanks for the super fast fix!

If for some reason it is of interest to you, I could still recompile the older version and provide a backtrace of the crash. But as far as I'm concerned, all's well again.
Thanks!
