### ISSUE TITLE
Fedora 22 support

### ISSUE THREAD

**Issue by wolfv** [davidgfnet/whatsapp-purple#291]
Hey, 

there is currently no Fedora 22 variant on copr. Maybe you can press a button somewhere to compile it? Would be cool!

Wolf

**Comment by davidgfnet** [comment]
Please do not open such isses, since it's just platform specific packaging.

**Comment by WurdahMekanik** [comment]
You realize that different releases have different versions of the dependencies that are used to compile the source right? I use Fedora 22 and Arch Linux as well, if you aren't going to update the binaries, and in the interest of better supporting those who try to build your source, perhaps you can fulfill issue #298 and state the dependencies required to build, and also which versions you use in-house.

If you're going to whine about people asking for updated binaries, you can also just state that you are no longer maintaining official builds for future distro releases... after all, as you state in another issue "this is github, only source matters!" :)
