### ISSUE TITLE
After joining new, WhatsApp-user created group, pidgin's blist.xml includes unparsable binary data

### ISSUE THREAD

**Issue by hoehermann** [davidgfnet/whatsapp-purple#293]
I am using whatsapp-purple with pidgin on Ubuntu 14.04 64bit. Thank you for your awesome plugin. However, I encounter an issue.
How to reproduce:

1. Have a contact who uses the official WhatsApp client. Let's name her Alice.
2. Alice creates a new WhatsApp group.
3. Alice adds other WhatsApp users to the group.
4. Alice invites me to the group. We chat. Everything works fine until here.
5. Pidgin saves all contacts ("buddies") in an xml file `blist.xml`. whatsapp-purple passes unescaped binary content to this file. The `blist.xml` becomes unreadable and cannot be used any longer. 

The problematic `component` tag can be removed manually in an editor of choice. It seems, the tag is not recreated, so this happens once per group join only. It is usable, but manual xml file editing is still annoying.
An excerpt of a damaged file looks like this. I cannot paste binary content to github, I replaced the binary string with "BINARY".
```xml
<chat proto='prpl-whatsapp' account='49myphonenumber'>
	<alias>Pidgin-Defined Alias</alias>
	<component name='id'>49creatorphonenumber-unknownnumber</component>
	<component name='owner'>49creatorphonenumber</component>
	<component name='subject'>Creator-Defined Subject</component>
	<component name='admins'>BINARY</component>
	<setting name='gtk-mute-sound' type='bool'>0</setting>
</chat>
```
Further information (possibly containing personal data) can be given to davidgf upon private request.

**Comment by davidgfnet** [comment]
What version are you using? Version 0.8.3 will probably generate random data (due to a bad pointer not being initialized) and it might be prone to dump non ascii data. Can you check please?
I'm pretty sure it is because of this, since admins is just a phone list and "owner" works well.

**Comment by hoehermann** [comment]
I was using version 0.8.2 . That was stupid. You update faster than I pull. ;) I compiled 0.8.4 and will check as soon a contact of mine is willing to cooperate.

**Comment by hoehermann** [comment]
Yes, in version 0.8.4 the issue is solved. The admin field now contains the actual admin phone number. Thank you very much.
