### ISSUE TITLE
Cannot compile in Linux ARM

### ISSUE THREAD

**Issue by pickfire** [davidgfnet/whatsapp-purple#297]
Hi, when I execute `make`, I get the following errors:
```
gcc -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/libpurple -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -o imgutil.o imgutil.c
imgutil.c:2:23: fatal error: FreeImage.h: No such file or directory
compilation terminated.
Makefile:45: recipe for target 'imgutil.o' failed
make: *** [imgutil.o] Error 1
```
I hope that there is a dependencies list in README. And is *whatsapp-purple* able to be compiled in **ARM architecture**?
```
Linux alarmpi 4.0.8-3-ARCH #1 SMP PREEMPT Wed Jul 15 19:11:50 MDT 2015 armv7l GNU/Linux
```

**Comment by davidgfnet** [comment]
@pickfire Man, install dependencies... Or even better, use "search", this issue has been reported at least a couple times before.

**Comment by pickfire** [comment]
Yeah, most of the projects will include a lists of dependencies in the README.
