### ISSUE TITLE
Ciphered message received

### ISSUE THREAD

**Issue by TheFatal** [davidgfnet/whatsapp-purple#303]
hi, i compiled source, and installed whatsapp-pidgin - its ok, but i cant recieve messages from my buddies, i see only "Ciphered message received" message :( how can i fix it ?

**Comment by wasucks** [comment]
I have the exactly same problem, I got the text "[Ciphered message received]" (with brackets) in private chats.
Sending messages to the same buddy works ok.

**Comment by Aeronaut** [comment]
Same here... 

WhatApp finally uses some kind of encryption, what is not bad at all... IF it would be more transparent.

**Comment by benkinooby** [comment]
Using Resource "S 40-2.12.11-433" works for me. (I suspect that this disables encryption though...)

https://github.com/davidgfnet/whatsapp-purple/issues/179

**Comment by flipmess** [comment]
it's S 40-2.12.11-443 that's working here.
is whatsapp now using textsecure otr encryption?

**Comment by evanomondi** [comment]
Hi. Am also having this same problem. Someone please explain to me how to solve this

**Comment by phervieux** [comment]
I think whatsapp purple doesn't manage encrypted messages.

**Comment by flipmess** [comment]
well there's textsecure implementation for desktop: https://github.com/janimo/textsecure
whatsapp is supposed to be using the same encryption.

**Comment by rodpmaia** [comment]
Work for me!!!
S 40-2.12.11-433

flipmess commented 14 days ago

it's S 40-2.12.11-443 that's working here. nope. it's S 40-2.12.11-433 ...sry...
is whatsapp now using textsecure otr encryption?

**Comment by evanomondi** [comment]
tried adjusting to this S 40-2.12.11-433 also and it worked.

On 20/11/2015, rodpmaia <notifications@github.com> wrote:
> Work for me!!!
> S 40-2.12.11-433
>
> flipmess commented 14 days ago
>
> it's S 40-2.12.11-443 that's working here. nope. it's S 40-2.12.11-433
> ...sry...
> is whatsapp now using textsecure otr encryption?
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/davidgfnet/whatsapp-purple/issues/303#issuecomment-158420778


-- 

About Me |  <http://www.evantech.co/#!/about> My Portfolio  |
<http://www.evantech.co/#!/portfolio> Contact Me
<http://www.evantech.co/#!/contacts>
[image: Like our Electronics fun page]
<https://www.facebook.com/EvanTechn> [image:
Follow us on twitter] <https://twitter.com/EvanTechnology> [image: Add
Jumia on Google+]
<https://plus.google.com/b/101642258208450678535/101642258208450678535/about?hl=en>

**Comment by programacion-web** [comment]
Work for me!!!
S 40-2.12.11-433

**Comment by vinipsmaker** [comment]
> Work for me!!!
> S 40-2.12.11-433

`S 40-2.12.11-433` worked for me as well.

**Comment by rodpmaia** [comment]
my number blocked for whatsapp "server remote disconnect" by yowsup number
is blocked :(

2015-11-25 6:28 GMT-03:00 Vinícius dos Santos Oliveira <
notifications@github.com>:

**Comment by kaptoxic** [comment]
```S 40-2.12.11-433``` worked.

**Comment by Aeronaut** [comment]
Remember: "Work" means in this case, that there is absolutly no P2P encryption from and to your Client.

**Comment by teertinker** [comment]
for me, neither S 40-2.12.11-433 nor S 40-2.12.12-433 worked... the problem persists. It came from one day to another without any software changes.

**Comment by davidgfnet** [comment]
@teertinker Cheer up guys! Ciphered messages support coming really soon :D

**Comment by kolAflash** [comment]
Looks like I'm having similar problems like "teertinker". At least when receiving messages from Android (didn't test other platforms) I'm getting: "[Ciphered message received]"

**Comment by davidgfnet** [comment]
Current HEAD supports ciphered messages, please recheck with an updated version. Remember to use the default resource!

**Comment by vinipsmaker** [comment]
> Current HEAD supports ciphered messages, please recheck with an updated version. Remember to use the default resource!

Can you tag a new version, @davidgfnet? So I can update the ArchLinux package?

**Comment by davidgfnet** [comment]
I have to push a couple of commits before tagging. There is a new protocol update as well (WA1.6) that I want to roll out on the same version. I'm pretty sure WA1.5 will stop working soon :D so we need both axolotl AND WA1.6

**Comment by He1my** [comment]
using Resource "S 40-2.12.11-433" , "S 40-2.12.11-433" and even tried Resource "S 40-2.13.30-433", all results on the server closing the connection as of yesterday , setting the Resource back to "Android-2.12.326-443" it connects just fine but we are back with getting the "[Ciphered message received]" for any incoming messages, any ideas on how to get it working now temporarily until a version with both axolotl AND WA1.6 is ready?

**Comment by kolAflash** [comment]
Just compiled the current version from Git (default branch). And after removing the client version/resource line from accounts.xml, it became "Android-2.12.419" by the new plug-in version.

Looks like it's working fine now! (OS is Linux - sorry I don't know how to compile for Windows)
Login is working and I can read messages (no more "Ciphered message...").

@davidgfnet
Thanks for the great work!

**Comment by stef204** [comment]
Running Pidgin 2.10.12 (libpurple 2.10.12) on Linux x86_64.

I have been able to run whatsapp-purple without a hitch for weeks now, using S 40-2.12.11 as the resource and c2.whatsapp.net as the server on port 443.

A few days ago, it stopped working with "server closed connection" error message.
I then changed resource to Android-2.12.419 and I could log in again.

However, while I could _send_ messages, I could not _read_ them, getting the _"Ciphered Message Received"_  error message.

Recompiling master branch after reading this thread, the only change I noticed was that the above _"Ciphered Message Received"_ was gone but messages were just blank, so still cannot see/read them.

I have been checking master branch and using git pull and recompiling after changes/commits are pushed to master but nothing changes whatsoever.

**Even with new version pushed yesterday (0.9), the problem persists.**

I could add that the messages I have been sent (and cannot read) are coming from iPhones.  Possibly, the implementation of the encryption is somewhat different than in Android version....  (I doubt it.)

Would appreciate some feedback re. troubleshooting this.

**Comment by davidgfnet** [comment]
@stef204 For the ones compiling from source. Make sure you get what you want. Do not pull, but clone the repo. Or use "make cleanall"

**Comment by stef204** [comment]
OK, this was the problem: I didn't test it with enough contacts; one of my contacts (iPhone) contacted me today and it worked just fine, both ways.

The other contact (iPhone) whose message I could not read had not upgraded **their** whatsapp version and this was the cause of the problem.

As soon as that contact upgraded, the problem disappeared.

So, the problem was not whatsapp-purple but the failure to upgrade on other side.

Thanks for feedback and great work on this implementation.
