### ISSUE TITLE
Ciphered message received in a groupchat

### ISSUE THREAD

**Issue by towlie** [davidgfnet/whatsapp-purple#307]
It happened on a 2 month old group with 3 people. At the same time I got a readable message inside a 1 year old group.

**Comment by towlie** [comment]
I didn't hear that they added encryption for groupchat. Maybe there is a false positive in your encrypted message commit?

**Comment by Raaff** [comment]
Same problem here, with a fresh build: `[Ciphered message received]`.
This happened to me in a small group-chat (3 people) four days ago, while I still received messages from the other person in the same chat. In a larger chat I could still receive message from the person who gave me a ciphered message in the small chat.

**Comment by towlie** [comment]
@Raaff Does it still happen to you? Today I was able to see messages from a 3 people groupchat again. So it might be fixed on whatsapp side.

**Comment by Raaff** [comment]
No, I changed my Resource string to "S60-2.12.21", which solved the problem for me. (However, I'm now getting the "unable to parse resource" message...)

**Comment by benkinooby** [comment]
Using Resource "S 40-2.12.11-433" works for me.

source: https://github.com/davidgfnet/whatsapp-purple/issues/179

**Comment by pabloscasas** [comment]
In a group of 5 people, resource Android-2.12.176-433 gives [Ciphered message received]. Changing to S 40-2.12.11-433 fixes the problem.

**Comment by redstar3** [comment]
@benkinooby @pabloscasas  not working here, still can't received message. is 443 not 433 right ?

**Comment by pabloscasas** [comment]
Sorry for the mistake; you are right redstar3: is 443.

**Comment by Zap123** [comment]
It's happening to me now in a 4 people group. I can't read messages from my friend who are using android.

**Comment by davidgfnet** [comment]
Current HEAD should support this (i've tested and it works for me, might have some issues though).
