### ISSUE TITLE
Compilation error, missing FreeImage.h

### ISSUE THREAD

**Issue by Smile4ever** [davidgfnet/whatsapp-purple#309]
[geoffrey@msi-laptop whatsapp-purple]$ LANG=en make
gcc -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC -I/usr/include/libpurple -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -o imgutil.o imgutil.c
imgutil.c:2:23: fatal error: FreeImage.h: No such file or directory
compilation terminated.
Makefile:45: recipe for target 'imgutil.o' failed
make: *** [imgutil.o] Error 1

**Comment by davidgfnet** [comment]
Dup #285!
