### ISSUE TITLE
sometimes "Last Seen info" change to other values

### ISSUE THREAD

**Issue by angelbladex** [davidgfnet/whatsapp-purple#310]
Hi!

if you move the cursor over the contacts for see "last seen" info, sometime this value is changed when you choose other(s) contact(s) and return to first contact , value change. 

This happen too when open a new conversation and mover cursor over avatar from your contact.

**Comment by cleitonss** [comment]
This happens to me too...

**Comment by pabloscasas** [comment]
The same happens to me since last Fryday Aug 21..

**Comment by angelbladex** [comment]
i tested other way, i started a conversation with a friend, after 1 hour, i checked "Last seen" info and my friend had "10 days, 3 hours...." WTF?

**Comment by axel21a** [comment]
This happens to me too..in italy

**Comment by davidgfnet** [comment]
Is it happening with yowsup as well? Sounds like some update on the last seen logic.

**Comment by ahmedtabrez** [comment]
@davidgfnet, Yes this is happening with yowsup as well. Most probably there's an update in the last seen logic.

**Comment by axel21a** [comment]
the problem still persists, as the answer
@davidgfnet help

**Comment by giordano** [comment]
Bug #315 has been fixed, this ticket should be closed too.
