### ISSUE TITLE
I am not receiving text message whatsapp

### ISSUE THREAD

**Issue by guilhermealano** [davidgfnet/whatsapp-purple#312]
Hello, I'm not getting the message in pidgin whatsapp but can not send.
I can receive audios or pictures, but text does not. Already changed my phone number, but there was no change.

**Comment by casualboy** [comment]
Same problem here. I can receive images, audio but not text messages. I can send messages but can't receive text messages. When a message is sent from phone, it shows that I've read message but nothing is displayed on my side. 

Purple Version: 0.85

OS: Ubuntu 14.04

Port: 443

Resource: Android-2.12.176-443

**Comment by radasbona** [comment]
Also the same Problem. Linux Mint 17, Port: 443, Resource: Android-2.12.176-443. Via Launchpad ppa.

**Comment by morningpee** [comment]
I can send messages but not receive them. Using python-yowsup-git v2.3.185.r9.g77330b8-1 on Arch Linux 4.1.3-1, port 443, resource Android-2.12.176-443

**Comment by davidgfnet** [comment]
I didnt get that one. You say you cannot receive messages, right? Does that happen with pidgin plugin or yowsup?

**Comment by guilhermealano** [comment]
Happens in pidgin, I can usually send the message, the recipient receives normally, but the answer did not get the message and is read as the staff whatsapp who answered.

But if the person responds with an audio or video, get normally.

Att.,
Guilherme Alano

**Comment by davidgfnet** [comment]
@guilhermealano Some people mention that requesting new password and chaning the resource makes it go away

**Comment by guilhermealano** [comment]
unsuccessfully.

**Comment by morningpee** [comment]
@davidgfnet Sorry, wrong package.  I'm using whatsapp-purple with pidgin, v0.8.5-1. I too can receive images but not SMS, and sending SMS works for me.

**Comment by radasbona** [comment]
Not even Linux Mint, also Windows 7. OS, Pidgin and Plugin up to date. Everything works, except receiving text. Nothing shows up, and my opponent get's his message marked read.

**Comment by walidsa3d** [comment]
I can't receive messages from others, I can only send them.

**Comment by morningpee** [comment]
After compiling directly from the git source (including commit 415c68f), using resource "S 40-2.12.11-433", and using server c3.whatsapp.net (not sure if that last step is necessary), I can send and receive messages properly.
#303

**Comment by redstar3** [comment]
same here can't receive message. i try using S 40-2.12.11-443 still not working

**Comment by guilhermealano** [comment]
@davidgfnet how to solve this problem? Any solution?

**Comment by radasbona** [comment]
resource "S 40-2.12.11-433" works on my linux laptop! Sorry can't check win7 at the moment. my graphic card is damaged. :-(

**Comment by morningpee** [comment]
@redstar3

433, not 443

**Comment by redstar3** [comment]
@morningpee i'm use port 443 and resource S 40-2.12.11-433 not works, "unable to parse resource". still can't received message

**Comment by davidgfnet** [comment]
@redstar3 Spaces?

**Comment by davidgfnet** [comment]
I started implementing the new encryption in the axolotl branch. People familiar with Linux can contact me so we can organize a bit of a testing.
The idea is to checkout that branch, compile it using "debug" and test it a bit. I can give more instructions to people willing to help.

**Comment by assegaf** [comment]
@davidgfnet if you need a sample dump Android Latest client tx and rx data let me know in here, my number is disposable so it wont matter if private and public key exposed in here,

**Comment by redstar3** [comment]
@davidgfnet yes exactly http://i.imgur.com/n3TujHw.png

**Comment by guilhermealano** [comment]
hello, any news? or upgrade?

**Comment by davidgfnet** [comment]
Current HEAD supports axolotl, so now you can receive ciphered messages (hopefully, it's WIP)
