### ISSUE TITLE
not authorized whatsapp account

### ISSUE THREAD

**Issue by yitzan** [davidgfnet/whatsapp-purple#313]
Hello

I downloaded pidgin to my computer in order to use WhatsApp. (I don't have a smartphone).
When I try to connect to the program, I see at the bottom of the screen"not-Authorized".

if I can't use WhatsApp, I will be happy to close my account, in order not to confuse friends.

How can I do this?
Thank you very much,

**Comment by benkinooby** [comment]
Hi,

"not-authorized" is a strong indicator for wrong password or the fact that whatsapp blocks your account (e.g. they noticed that you're not using the official whatsapp client and decided to block you).

How to find out your password and whether you're blocked or not:
Use yowsup [1] to register your account [2] and watch the messages you get as reply to your commands (the whole process requires 2 commands). If one of them has the word "blocked" in them, then you know that whatsapp is blocking you on purpose. If you don't see anything "block"-related write down the password string you'll see and use it in pidgin.

What to do if you're blocked:
Your only way to resolve that is to ask whatsapp [3] to unblock you. Most likely they will ask you for a screenshot that shows that you're using the official WhatsApp software. If you don't have a smartphone you can use an android emulator [4] to emulate a smartphone where you install and register whatsapp.

Further information:
If you get Whatsapp to work in pidgin but only see "[Ciphered message received]" you have to change your client resource [5]. If you don't get whatsapp to work you can still use the facebook chat via pidgin or use xmpp services right away [6]. There are many free xmpp servers [7]

Hope that helps!

[1] https://github.com/tgalal/yowsup
[2] https://github.com/tgalal/yowsup/wiki/yowsup-cli-2.0#yowsup-cli-registration
[3] support@whatsapp.com
[4] https://developer.android.com/sdk/index.html#Other download the "SDK Tools Only" for your platform. If you have the SDK up and running use one of the predefined virtual devices with Android 4.4.2. 
[5] Accounts -> Manage Accounts -> Edit whatsapp account -> Advanced -> Resource: change it to "S 40-2.12.11-433" (without the " but with the space)
[6] xmpp is the "mother" of chat protocolls (besides IRC) and open for everyone without any restrictions.
[7] http://www.jabber.org/

**Comment by compressorhead** [comment]
Hello:

It looks that we are again lock out from wsp servers:

(23:18:47) proxy: Attempting connection to 173.192.222.170
(23:18:47) proxy: Connecting to c3.whatsapp.net:443 with no proxy
(23:18:47) proxy: Connection in progress
(23:18:47) proxy: Connecting to c3.whatsapp.net:443.
(23:18:47) proxy: Connected to c3.whatsapp.net:443.
(23:18:50) connection: Connection error on 0xb8b78798 (reason: 2 description: not-authorized)
(23:18:50) account: Disconnecting account XXXXXXXXXX (XXXXXXXXXX)
(23:18:50) connection: Disconnecting connection 0xb8b78798
(23:18:50) connection: Destroying connection 0xb8b78798

None C1 C2 or C3 works, doesnt matter wich user agent. yowsup/smartphone works, so my account is not blocked.

**Comment by anmol26s** [comment]
Hi
I was getting Not Authorized while login in.
As  benkinooby  said: [5] Accounts -> Manage Accounts -> Edit whatsapp account -> Advanced -> Resource: change it to "S 40-2.12.11-433" worked for me.

Thanks benkinooby

**Comment by ildar** [comment]
Thumbs up! Worked for me too!

**Comment by hugoroy** [comment]
It works for me as well; thank you

**Comment by maneesh654** [comment]
Worked fine for me too. Thanks :)

**Comment by kingjr** [comment]
me too, thanks!

**Comment by ildar** [comment]
hey,
"S 40-2.12.11-433" stopped working for me today.
Any more ideas?

**Comment by davidgfnet** [comment]
See #308, they are related so I'll consider them duplicates
