### ISSUE TITLE
Random lastseen of all the contacts

### ISSUE THREAD

**Issue by ahmedtabrez** [davidgfnet/whatsapp-purple#315]
A few days back, My account had suddenly stopped working with unauthorized error, I regenerated the password and everything is back on track except the last seen timestamp. Sometimes it is a few hours ago and sometimes it is few months ago. Everything was fine before. 

Note: When buddies come online, I get a pounce and I get green light next to their names.

Is anyone experiencing this strange behavior? (I am on windows and use whatsapp4pidgin-0.8.4)

**Comment by ahmedtabrez** [comment]
Update: I just checked with yowsup library. 
<code>
/contact lastseen 919xxxxxxxxx
</code>
The result is the same. Sometimes a few thousand seconds ago, sometimes a few ten thousands ago, even the buddies who chatted with me a few minutes ago.

**Comment by czietz** [comment]
This was reported in #310 as well. 

I can confirm this, too. It even happened to me the same way as in your case. I had to regenerated the password and since then "last seen" times are completely random.

**Comment by ahmedtabrez** [comment]
@czietz, looks like there is some change in whatsapp protocol .... Because yowsup too is giving the same result when running:
<code>
/contact lastseen 919xxxxxxxxx
</code>

**Comment by angelbladex** [comment]
Similar to #310

**Comment by mgp25** [comment]
Its was solved 1 month ago: https://github.com/WHAnonymous/Chat-API/issues/938

**Comment by axel21a** [comment]
I assume then that will also update the version of the plugin for Windows
