### ISSUE TITLE
you can only see empty groups on latest master

### ISSUE THREAD

**Issue by towlie** [davidgfnet/whatsapp-purple#319]
On latest master you only see empty groups (no participants)
Windows 7 (I copied the c and cxx lines from the updated makefile)

**Comment by davidgfnet** [comment]
Ops! Let me check, it is very likely that I introduced several regression
in the last commit :D

**Comment by davidgfnet** [comment]
If you see any other issue, please let me know. Thanks!

**Comment by towlie** [comment]
Well I' don't know if this is worth an other issue but when closing group I see this debug message:
(23:26:53) server: Leaving room: 
(23:26:53) GLib: g_hash_table_destroy: assertion `hash_table != NULL' failed
(23:26:53) GLib: g_hash_table_destroy: assertion `hash_table != NULL' failed

**Comment by davidgfnet** [comment]
Yeah I thing this has been there for a while... Does it cause pidgin to crash?
Since the last cleanup I don't get any crashes (I used to get some random crashes when closing Pidgin).

**Comment by towlie** [comment]
No, it's just a warning.
