### ISSUE TITLE
Packaging for Debian

### ISSUE THREAD

**Issue by alexvong1995** [davidgfnet/whatsapp-purple#321]
Hi everyone,

First, thanks for this wonderful program! I am not using it anymore since I don't need whatsapp anymore. Hopefully I will switch to IRC someday later, but I am busy right now. I just want to know if you would like to see it on Debian. If you think it is OK, I will fire up an Intent To Package bug report and do the work when I have more free time.

Besides, I notice there are some files not having copyright notice, are they all licensed under GPL-2+ as stated in `debian/copyright`?

**Comment by davidgfnet** [comment]
@alexvong1995 There is a request for packaging already, I did it myself.

**Comment by alexvong1995** [comment]
Thanks for replying! Have you sent a RFS bug report yet? Also, what do you think about the files not having copyright notice?

**Comment by alexvong1995** [comment]
Sorry, maybe what I have said is not clear. Let's close this issue for now.
