### ISSUE TITLE
Sending messages to a group doesn't work

### ISSUE THREAD

**Issue by towlie** [davidgfnet/whatsapp-purple#323]
It looks like it just sends nothing. I asked the others via PM and they see nothing. Private messages do work. Oh and I am admin in that group. Receiving does work.

(Using latest master)

**Comment by towlie** [comment]
@davidgfnet I tested the latest release version and it works there so it must be something introduced by your rewrite/cleanup.

**Comment by towlie** [comment]
Is it possible that you can add "server received" ticks (one tick) for group messages? Like you did for privat messages.

**Comment by pabloscasas** [comment]
I cannot send messages to groups either.

**Comment by davidgfnet** [comment]
Ticks should be possible, I can take a look at that, but the next feature is gonna be axolotl, so I'm just focusing on that except for bugfixes.

**Comment by towlie** [comment]
I had this idea when I realized that noone was able to read my group messages. (after days) I will make an issue about this feature when axolotl is ready.
