### ISSUE TITLE
Documentation on how to use this outside of pidgin/libpurple?

### ISSUE THREAD

**Issue by pedrocam** [davidgfnet/whatsapp-purple#324]
Hi, 

I find that this DLL is the only API for whatsapp that is working for me in the moment. I am using the following settings posted earlier in another thread: http://i.imgur.com/n3TujHw.png

With that in mind, I want to write a software based on this API/DLL but I am uncertain of how to do this since this is written for libpurple/pidgin. Do I have to write a libpurple chat program or is there some documentation on how to use this DLL within C, .NET, python, PHP or any other languages?

Thanks and keep up the good work! Much appreciated!

**Comment by davidgfnet** [comment]
Sorry but I have to close this. This is a libpurple plugin and I do not intend to target it as a separate lib. There are many other implementations of whatsapp API in many other languages, google is your friend.
