### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by mkolchin** [davidgfnet/whatsapp-purple#326]
(06:03:07) account: Connecting to account xxxxxxxxxxx.
(06:03:07) connection: Connecting. gc = 0x8e25238
(06:03:07) whatsapp: logging in xxxxxxxxxxx
(06:03:07) dnsquery: Performing DNS lookup for e8.whatsapp.net
(06:03:07) dns: Successfully sent DNS request to child 1091
(06:03:07) dns: Got response for 'e8.whatsapp.net'
(06:03:07) dnsquery: IP resolved for e8.whatsapp.net
(06:03:07) proxy: Attempting connection to 158.85.58.109
(06:03:07) proxy: Connecting to e8.whatsapp.net:443 with no proxy
(06:03:07) proxy: Connection in progress
(06:03:07) proxy: Connecting to e8.whatsapp.net:443.
(06:03:07) proxy: Connected to e8.whatsapp.net:443.
(06:03:08) util: Writing file prefs.xml to directory /home/user/.config/purple
(06:03:08) util: Writing file /home/user/.config/purple/prefs.xml
(06:03:11) connection: Connection error on 0x8e25238 (reason: 0 description: Server closed the connection)
(06:03:11) account: Disconnecting account xxxxxxxxxxx (0x8203b60)
(06:03:11) connection: Disconnecting connection 0x8e25238
(06:03:11) connection: Destroying connection 0x8e25238
(06:03:13) util: Writing file accounts.xml to directory /home/user/.config/purple
(06:03:13) util: Writing file /home/user/.config/purple/accounts.xml

**Comment by mkolchin** [comment]
All OK. Decided across WART.

**Comment by SergeyDjam** [comment]
This does not help

**Comment by mkolchin** [comment]
Мне помогло.

**Comment by SergeyDjam** [comment]
Несколько раз сделал запрос, несколько раз переактивировал, несколько раз сменил пароль.
Проходит какое-то время. Отваливается от сервера (Server closed the connection) и через несколько попыток подключения пишет что ошибка в пароле или что-то подобное, и полностью плагин отключается (not-authorized) 
сервер c3.whatsapp.net

**Comment by mkolchin** [comment]
У меня вообще никакого сервера не стоит. Сначало мучался с паролем - там после телефона внизу нажать blabla и все. Что за дистр. у меня Simply Linux кстати сам на днях собирал в репозиторий.

**Comment by SergeyDjam** [comment]
ROSA Fresh. Пакеты сам собираю. С паролем не мучаюсь, так как WART решает все проблемы. Сервер ручками пришлось указывать, так как без указания, во всяком случае ранее не работал. 
whatsapp-purple 0.8.6
pidgin-2.10.11

**Comment by mkolchin** [comment]
Nfr ds bp ROSA? :)

**Comment by SergeyDjam** [comment]
Что?

**Comment by mkolchin** [comment]
C ROSA незнаком.

**Comment by davidgfnet** [comment]
Ok guys enough...
