### ISSUE TITLE
Group chat, sending files

### ISSUE THREAD

**Issue by Woodzrul** [davidgfnet/whatsapp-purple#328]
Hello

I understand that this issue has been discussed before, but I was curious to know if there were any plans on resolving the issue whereby you are unable to send files to group chats.

Thanks in advance

**Comment by davidgfnet** [comment]
@Woodzrul File sending is not supported in Pidgin (libpurple). Some hackiness to resolve this would be needed. I suggested to modify pidgin to allow such a thing, but it takes time to implement and upstream. Any volunteers?

**Comment by Woodzrul** [comment]
Appreciate the prompt response David. I honestly would not know where to begin. Hopefully you'll get a response re the above and a solution soon. :-)

Though sending files individually is fine, just group chats.

**Comment by Woodzrul** [comment]
Hi David. Hope you're looking forward to Christmas. Did anyone PM you re the above? Would be great to get this feature implemented. :-)

**Comment by davidgfnet** [comment]
Go to pidgin's IRC channel and bug the developers there with this. You may get lucky.
