### ISSUE TITLE
[Ciphered message received] only in reply

### ISSUE THREAD

**Issue by SergeyDjam** [davidgfnet/whatsapp-purple#331]
why in reply this message? 
otr-plugin off

**Comment by xavvo** [comment]
I get the same here on Mint (jessie/sid) x86_64 with Pidgin 2.10.9 (libpurple 2.10.9).
Fresh compile of f41d3c0f8.

It seemed broken since I update to 0.8.6, so I recompiled. Now same problem.

cu

**Comment by SergeyDjam** [comment]
pidgin 2.10.11 (libpurple 2.10.11)
whatsapp-purple 0.8.6
ROSA Linux x86_64 
my config now

**Comment by xavvo** [comment]
I researched and found https://github.com/davidgfnet/whatsapp-purple/issues/312 
use the resource as in the last message there, it will do until encryption works :)

**Comment by hajhouj** [comment]
Hi,

I have the same issue in the windows version of the plugin, I cannot receive clear messages just "[Ciphered message received]". 
The installer is whatsapp4pidgin-0.8.6.exe. It's precompiled so I can't change the resource file, please can you solve this issue?

**Comment by davidgfnet** [comment]
You shouldnt use phone numbers that have been used with whatsapp in the past (other clients will send them ciphered with a key only your phone understands).
You CAN change the resource in the account info. It's not hardcoded.

**Comment by SergeyDjam** [comment]
I changed resource for my account, but it did not help

**Comment by hajhouj** [comment]
Can you please explain me how to change the resource in the account info. and is there a way to reinitialize the key so whatsapp will work with pidgin and anymore with the phone.

**Comment by SergeyDjam** [comment]
Pidgin - Ctrl+A - you whatsapp account - Advanced - resource

**Comment by hajhouj** [comment]
Thanks for the info

**Comment by hajhouj** [comment]
Problem resolved thanks you guys.
The solution is to set resource to "S 40-2.12.11-433".

**Comment by SergeyDjam** [comment]
Mistic. Work now.
