### ISSUE TITLE
change client-version to Android-2.12.326-443

### ISSUE THREAD

**Issue by kolAflash** [davidgfnet/whatsapp-purple#336]
My client version number was explicitly set to: Android-2.12.176-443

Before 6 hours login was still working. But now I got the message "not-authorized".

Removing the client-version (resource) from accounts.xml didn't helped.

But setting the client-version to "Android-2.12.326-443" helped!

**Comment by jasonwee** [comment]
nice, happened here too and the solution works for me too! :) thank you.

**Comment by Jay1506** [comment]
changing client-version "Android-2.12.326-443" not give me a solution and stayed "not authorized"
can you give here your advance setting guyz?

**Comment by jasonwee** [comment]
not authorized could be ban though, i had that once and i try to register. but not-authorized could means other things too.

**Comment by disearth** [comment]
Solution worked thanxxx

**Comment by ariasrodolfo** [comment]
--"setting the client-version to "Android-2.12.326-443" "--
same problem and the solution works for me too!!!  Thanks.!!

**Comment by hoehermann** [comment]
Works for me. Thank you.

**Comment by farseenabdulsalam** [comment]
This is because WhatsApp for Android v2.12.17 became obsolete a few days ago.

**Comment by disearth** [comment]
@farseenabdulsalam thank for info.

**Comment by disearth** [comment]
Again the same issue occurred.

**Comment by sbourdeauducq** [comment]
:+1: same problem and same solution here.

**Comment by rigid** [comment]
will the default client version be updated in the near future? I couldn't figure out how to change the resource when using spectrum2 without nasty patching.

**Comment by disearth** [comment]
not working,...

**Comment by Jay1506** [comment]
same as me,didn't work

**Comment by dsultanr** [comment]
this one Android-2.12.366-443 working for me

**Comment by disearth** [comment]
Thanks @dsultanr

**Comment by dariox86** [comment]
I've always used S 40-2.12.11-443 and it has always worked. Android-2.12.366-443 works for me as well. I have the same problem as @rigid, I am unable to change it in Spectrum 2 without patching the source code.

**Comment by disearth** [comment]
Android-2.12.366-443  & S 40-2.12.11-443 not woking for me...

**Comment by disearth** [comment]
Any solution ?

**Comment by Vmyamoto** [comment]
Any Solution? Android-2.12.366-443 and Android-2.12.326-443 don't work for me. :-1:

**Comment by sbourdeauducq** [comment]
``S 40-2.12.11-443`` works here.

**Comment by Vmyamoto** [comment]
how? i put S 40-2.12.11-443 in RESOURCE @sbourdeauducq ? SORRY, i'm noob

**Comment by Vmyamoto** [comment]
I put S 40-2.12.11-443 in Resource and don't work. :/ I use Windows Xp Pidgin 2.10.11

**Comment by disearth** [comment]
I am also using PIDGIN windows plugin,.

**Comment by dsultanr** [comment]
2.12.366 definitely works

![1234](https://cloud.githubusercontent.com/assets/1683476/11724211/b2af6c40-9f83-11e5-8218-56c964bb0007.jpg)

**Comment by disearth** [comment]
I have also used  Android-2.12.366-443 but it is not working...are using any type of VPN or proxy to run ???

**Comment by dsultanr** [comment]
no. direct connection

**Comment by davidgfnet** [comment]
I'm a bit tired of repeating this but, make sure that the phone number and the password are OK. Most people fail to write the number properly (prefixes and such) and others just get a wrong password. I know it's not straightforward but remember this plugin borders "the legal" :)
Also remember that some numbers are blocked by whatsapp Inc. since they try to detect and block people using non-official clients. Hope it helps.

**Comment by dsultanr** [comment]
+1, you should check twice the number and the password. Use WART to make the new password if nothing helps.
And the last thing - current up to date version number could be found on Whatsapp's Android download page:
https://www.whatsapp.com/android/

![1234](https://cloud.githubusercontent.com/assets/1683476/11724590/02d47402-9f86-11e5-9e49-01cf09ff1b83.jpg)

**Comment by Vmyamoto** [comment]
my number and my password are ok. the problem is not this. i try 2.12.382

**Comment by disearth** [comment]
Everything is Ok but PIDGIN plugin for whatsapp is not working fine with all the WhatsApp version metioned above :(

**Comment by farseenabdulsalam** [comment]
Resource: S 40-2.12.11-433 on PIDGIN WhatsApp works fine here

**Comment by kolAflash** [comment]
Also had to change my resource to: S 40-2.12.11-433

Else I always got a error-message: [Ciphered message received]
https://github.com/davidgfnet/whatsapp-purple/issues/331

**Comment by dsultanr** [comment]
Today something broken. I have a "server closed connection" on login attempt. Any thoughts?

**Comment by sbourdeauducq** [comment]
Same problem here.

**Comment by simgekim** [comment]
yes, something updated. new resource strings: Android-2.12.419-443 or S40-2.13.30-443
both working.

**Comment by dsultanr** [comment]
thanks! working

2016-01-26 11:41 GMT+03:00 simgekim <notifications@github.com>:

**Comment by sbourdeauducq** [comment]
:+1: S40-2.13.30-443 working here too. Thx

**Comment by hargev** [comment]
With resource strings: Android-2.12.419-443 or S40-2.13.30-443, I get [Ciphered message received]

**Comment by dsultanr** [comment]
same here

seems that we need enforce ciphered message feature development

2016-01-26 12:20 GMT+03:00 hargev <notifications@github.com>:
