### ISSUE TITLE
error if i run just "make"

### ISSUE THREAD

**Issue by AyushBhat** [davidgfnet/whatsapp-purple#340]
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
gcc -c  -O2 -Wall -Wno-unused-function -fPIC -DPURPLE_PLUGINS -DPIC  -o imgutil.o imgutil.c
imgutil.c:1:0: warning: -fPIC ignored for target (all code is position independent) [enabled by default]
imgutil.c:2:23: fatal error: FreeImage.h: No such file or directory
compilation terminated.
Makefile:46: recipe for target 'imgutil.o' failed
make: *** [imgutil.o] Error 1

**Comment by smacz42** [comment]
Try

`# dnf install libpurple-devel`
