### ISSUE TITLE
I bought whatsapp for windows yesterday but it does not works. 

### ISSUE THREAD

**Issue by Vmyamoto** [davidgfnet/whatsapp-purple#342]
Any solution? Help me please.

**Comment by disearth** [comment]
Does'nt working for me as well.

**Comment by wopaum** [comment]
what happens?

**Comment by djRechner** [comment]
I I used WART to register to Whatsapp. And i can't connect. When i try to connect i get:

**Comment by djRechner** [comment]
(18:50:41) whatsapp: logging in 528116098254
(18:50:41) dnsquery: Performing DNS lookup for e9.whatsapp.net
(18:50:41) dnsquery: IP resolved for e9.whatsapp.net
(18:50:41) proxy: Attempting connection to 169.54.55.214
(18:50:41) proxy: Connecting to e9.whatsapp.net:443 with no proxy
(18:50:41) proxy: Connection in progress
(18:50:41) proxy: Connecting to e9.whatsapp.net:443.
(18:50:41) proxy: Connected to e9.whatsapp.net:443.
(18:50:41) connection: Connection error on 04EFAE38 (reason: 2 description: not-authorized)
(18:50:41) account: Disconnecting account 528116098254 (01F176A8)
(18:50:41) connection: Disconnecting connection 04EFAE38
(18:50:41) connection: Destroying connection 04EFAE38

**Comment by davidgfnet** [comment]
Check closed issues, this has been reported many times. You can probably get around it changing the Resource string in the account settings.

**Comment by esdf** [comment]
i've registered my number & authed teh code with WART to get the password and now i keep getting "server closed connection".

i didn't buy whatsapp-purple, i've built it from source. also windows.

**Comment by davidgfnet** [comment]
New version fixes this hopefully. I will roll windows updates in a couple days. Closing for now. Once the new version comes out feel free to report new bugs and issues
