### ISSUE TITLE
Server closed the connection

### ISSUE THREAD

**Issue by TonyStark** [davidgfnet/whatsapp-purple#345]
Hello
Recently i register fresh whatsapp account, and get password using WART.
but whenever i try to put id/pass in pidgin i got error: "Server closed the connection"
anybody help me?

**Comment by davidgfnet** [comment]
Check your resource. Search in the issue list, it's been reported many times before

**Comment by TonyStark** [comment]
@davidgfnet i tried many resource, also change server and port.
but not helped ny one.

**Comment by maneesh654** [comment]
just changing the resource to S 40-2.12.11-433 works well

**Comment by TonyStark** [comment]
well that was also not worked.
now whatsapp banned my account so, no need to try more.
closing this issue

**Comment by maneesh654** [comment]
Does whatsapp ban accounts frequently??

**Comment by TonyStark** [comment]
@maneesh654 
yes, i just only request password one time.
by changing resources they think im using unofficial client, so they ban account

**Comment by SergeyDjam** [comment]
Oh, this problem to back :(
On release 0.8.6 and master (6cde8b4)... I d'nt change connection properties. But no connect...

**Comment by davidgfnet** [comment]
Check v0.9
