### ISSUE TITLE
axolotl: receiving images in groups asks for permission to receive the file

### ISSUE THREAD

**Issue by giordano** [davidgfnet/whatsapp-purple#349]
Today I upgraded the plugin to the latest version, with support for axolotl.

I just received an image in a group, but a pop-up showed up asking for permission to receive the file, then the image is shown twice in the log: the first time with the correct timestamp, address `https://davidgf.net/whatsapp/imgdec.php?url=...` (which can't be opened with a simple click, as it was before) and in thumbnail format, then another message with a wrong timestamp (1970-01-01 at 00:00, the Unix epoch), nothing as text and a larger image.

As it was before (single message with a thumbnail but you could click on the link to download the full size picture) was more comfortable.

Anyway thanks for your work!

**Comment by davidgfnet** [comment]
You can change that in the Account preferences (there is an option to receive files as attachments).
Also in my machine the link is clickable (both Linux & windows) so maybe you can share a screenshot.
Whatsapp has changed many things and it's not possible to use the "old" behaviour anymore

**Comment by giordano** [comment]
> You can change that in the Account preferences (there is an option to receive files as attachments).

Ok, I found it, thanks!  I'll close the issue after some more testing.

>Also in my machine the link is clickable (both Linux & windows) so maybe you can share a screenshot.

The link is clickable, but now I'm asked the program with which to open the file.  Probably it has to do with the fact that now there is no extension, and the desktop environment can't guess the program to handle it.  I think it isn't a problem on `whatsapp-purple` side.

I have another problem in group chats, reported as #350.

**Comment by davidgfnet** [comment]
That's an issue with the decoder service, it's not sendind the appropriate MIME type. I'll probably fix that at some point.

**Comment by giordano** [comment]
I confirm this isn't a bug at all, one simply needs to deactivate the option "Download pictures as attachments" in account settings.
