### ISSUE TITLE
finding password

### ISSUE THREAD

**Issue by danielb2** [davidgfnet/whatsapp-purple#351]
For some reason this was closed with no comment https://github.com/davidgfnet/whatsapp-purple/issues/343

I can't get this to work because I can't get a password. What's up? Help?

**Comment by davidgfnet** [comment]
I closed if for a reason. Told you to use WART on windows or yowsup in any OS.
http://lmgtfy.com/?q=yowsup+get+whatsapp+password
Was it that difficult?

**Comment by danielb2** [comment]
Actually, you closed it without specifying the reason, and I had already filed this. And I still didn't get anything working. So yes, it's difficult. Please help.

**Comment by danielb2** [comment]
Still didn't figure out how to do the yowsup-cli.  Not sure why it's hard to just explain it. Their documentation says nothing about how to get the password, but you recommended it. All I'm asking for is help

**Comment by danielb2** [comment]
nevermind. I finally used someone's windows machine

**Comment by danielb2** [comment]
Well, I got not-authorized.  I checked the password a large number of times. Made sure not to have any leading zeroes or any crap ... 1206 ... etc
