### ISSUE TITLE
Account banned after updating to 0.9

### ISSUE THREAD

**Issue by styxtwo** [davidgfnet/whatsapp-purple#360]
My account was banned a day after I updated to the 0.9 version. From what I'm able to gather from the other issues, this happens when you don't request a new password when changing resources.

This didn't happen previously when I changed resources, so perhaps the people at whats-app have been paying more attention lately.

Anyways, let this be a warning to everyone to always request a new password!

**Comment by assegaf** [comment]
what android version is your resource, if higher than 3.12.326 then its Protocol 1.6 version from official client, but whatpurple still using Protocol 1.5,

basically you went into a trap by whatsapp.

**Comment by davidgfnet** [comment]
@assegaf Whatsapp purple uses protocol 1.6 and simulates wharsapp 2.12.419

**Comment by assegaf** [comment]
yeah I did notice that, thanks also for updating wireshark-whatsapp, this two project is great.
