### ISSUE TITLE
Failing to build latest version

### ISSUE THREAD

**Issue by vanfanel** [davidgfnet/whatsapp-purple#365]
I'm trying to build latest version but I get this:

manuel@vader:~/src/whatsapp-purple$ make
make -C libaxolotl-cpp/libcurve25519
make[1]: Entering directory '/home/manuel/src/whatsapp-purple/libaxolotl-cpp/libcurve25519'
gcc -o src/curve25519-donna.o -c src/curve25519-donna.c -DLIBCURVE25519_LIBRARY -O2 -fPIC  -std=c99 
src/curve25519-donna.c: In function ‘curve25519_donna’:
src/curve25519-donna.c:854:1: internal compiler error: Segmentation fault
 curve25519_donna(u8 *mypublic, const u8 *secret, const u8 *basepoint) {
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:66: recipe for target 'src/curve25519-donna.o' failed
make[1]: *** [src/curve25519-donna.o] Error 1
make[1]: Leaving directory '/home/manuel/src/whatsapp-purple/libaxolotl-cpp/libcurve25519'
Makefile:62: recipe for target 'libaxolotl-cpp/libcurve25519/libcurve25519.a' failed
make: *** [libaxolotl-cpp/libcurve25519/libcurve25519.a] Error 2

Any idea on what's going on? I've been able to build versions so far.

**Comment by davidgfnet** [comment]
@vanfanel This is a compiler bug, GCC5 may be broken. Could you report to them?

**Comment by vanfanel** [comment]
@davidgfnet It was just a matter of upgrading GCC, now it builds! Closing this issue, thanks!

**Comment by davidgfnet** [comment]
@vanfanel Worth reporting just in case you hit a bug in GCC :D

**Comment by vanfanel** [comment]
@davidgfnet But it works with the latest GCC version available on Ubuntu: gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)
It's still a GCC 5 version, so does it make sense to report? Whatever was wrong, seems to be working now.

**Comment by davidgfnet** [comment]
@vanfanel It may be gone "by accident" but the underlying bug still be there. Sounds very ugly to get a segfault from gcc in such a very simple .c file. I guess it's worth isolating the test case and reporting, but if you can't reproduce it any more just forget about it :D

**Comment by vanfanel** [comment]
@davidgfnet I would have to go back to the previous version (I guess I could look at the apt logs or something to find out), and I can't reproduce it anymore, so I will forget about it.
