### ISSUE TITLE
No contacts being displayed in Pidgin

### ISSUE THREAD

**Issue by alejandrorusso** [davidgfnet/whatsapp-purple#387]
I have compiled and successfully installed whatsapp-purple from source. Pidgin see the plugin, I wrote my login credentials, I logged in (so Pidgin says "Available"), but none of my contacts are displayed. 

Any ideas? 
Regards!

**Comment by alejandrorusso** [comment]
Some info: Ubuntu 14.04, Pidgin 2.10.9 (libpurple 2.10.9)

**Comment by Docbroke** [comment]
you will have to add contacts manually, whatsapp pools contacts from phonebook in android but here no such option

**Comment by davidgfnet** [comment]
Yep, no contact sync on whatsapp, go ahead and add your contacts one by one :D
