### ISSUE TITLE
only receiving empty messages

### ISSUE THREAD

**Issue by koem** [davidgfnet/whatsapp-purple#388]
Hi!

There are many issues on not receiving anything - not even an empty message, but this one is different: All I receive is empty messages:

![auswahl_026](https://cloud.githubusercontent.com/assets/922495/13380890/dafc944e-de4d-11e5-801a-47cfa02d761c.png)

red: received, blue: sent

on the sender's side it looks like this, which is ok:

![screenshot_2016-02-28-19-03-11](https://cloud.githubusercontent.com/assets/922495/13380929/82926d5a-de4e-11e5-90d5-4c926c4a36b6.png)

* I created the account with yowsup
* receiver is set to Android-2.12.419
* OS is Ubuntu 14.04.3
* deb package is Version 0.9.0 from http://ppa.launchpad.net/whatsapp-purple/ppa/ubuntu trusty main

I can't compile my own version, because on Ubuntu I can't install g++ because of unmet dependecies

**Comment by davidgfnet** [comment]
If you really wanna help, try to build it using debug please.
