### ISSUE TITLE
Error in Build source on Ubuntu 15.10 x64

### ISSUE THREAD

**Issue by inthemix84** [davidgfnet/whatsapp-purple#396]
Hello, i can't build Whatsapp-Purple code on my Ubuntu 15.10 x64.

Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing `purple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
make -C libaxolotl-cpp
make[1]: Entering directory '/home/john/Desktop/Temp/whatsapp-purple/libaxolotl-cpp'
protoc --cpp_out=state protobuf/LocalStorageProtocol.proto
make[1]: protoc: Command not found
Makefile:72: recipe for target 'state/LocalStorageProtocol.pb.h' failed
make[1]: *** [state/LocalStorageProtocol.pb.h] Error 127
make[1]: Leaving directory '/home/john/Desktop/Temp/whatsapp-purple/libaxolotl-cpp'
Makefile:65: recipe for target 'libaxolotl-cpp/libaxolotl.a' failed
make: *** [libaxolotl-cpp/libaxolotl.a] Error 2

Some idea ??
Thank

**Comment by inthemix84** [comment]
Hello, i can't build Whatsapp-Purple code on my Ubuntu 15.10 x64.

$ make
Package purple was not found in the pkg-config search path.
Perhaps you should add the directory containing purple.pc' to the PKG_CONFIG_PATH environment variable No package 'purple' found Package purple was not found in the pkg-config search path. Perhaps you should add the directory containingpurple.pc'
to the PKG_CONFIG_PATH environment variable
No package 'purple' found
make -C libaxolotl-cpp
make[1]: Entering directory '/home/john/Desktop/Temp/whatsapp-purple/libaxolotl-cpp'
protoc --cpp_out=state protobuf/LocalStorageProtocol.proto
make[1]: protoc: Command not found
Makefile:72: recipe for target 'state/LocalStorageProtocol.pb.h' failed
make[1]: *** [state/LocalStorageProtocol.pb.h] Error 127
make[1]: Leaving directory '/home/john/Desktop/Temp/whatsapp-purple/libaxolotl-cpp'
Makefile:65: recipe for target 'libaxolotl-cpp/libaxolotl.a' failed
make: *** [libaxolotl-cpp/libaxolotl.a] Error 2

Some idea ??
Thank

**Comment by davidgfnet** [comment]
You are missing lots of devel packages such as libpurple-dev and protobuffers and many other stuff.
