### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by tahmeedhossain** [davidgfnet/whatsapp-purple#398]
I have downloaded the file. Now how do i install it? I am newb,so please help. 

I already have pidgin portable installed. I know it's directory. Now what?

**Comment by Imhotep-2700bc** [comment]
Depends on your operating system

**Comment by tahmeedhossain** [comment]
I use windows. please help.

**Comment by Imhotep-2700bc** [comment]
Sorry, I use Linux and I'm not familiar with Windows installations. Good luck.

**Comment by davidgfnet** [comment]
In any platform just copy DLL/SO files to plugins directory and make sure any dependencies (like FreeImage) are installed in your system lib dir (windows/system32 or /usr/lib)
