### ISSUE TITLE
User friendly ui for account registering with yowsup-cli

### ISSUE THREAD

**Issue by dtrunk90** [davidgfnet/whatsapp-purple#4]
I just created this issue: https://github.com/tgalal/yowsup/issues/134
So we could make a dependency and extend pidgins user interface for (auto) registering the account.

**Comment by davidgfnet** [comment]
There are many tools to do this, but I have one repo at whatsapp-tools which does this.
On top of that https://davidgf.net/whatsapp/pwd.html might also help
