### ISSUE TITLE
Unable to get password for Indian numbers

### ISSUE THREAD

**Issue by thefourtheye** [davidgfnet/whatsapp-purple#400]
I am from India, and when I give my phone number with country code in this page https://davidgf.net/whatsapp/pwd.html, it always says "Seems there was an error! Check your phone number again".

**Comment by davidgfnet** [comment]
Use WART, it should be up to date https://github.com/mgp25/WART
Or you can use yowsup alternatively.

**Comment by thefourtheye** [comment]
It looked like yowsup was working. But then pidgin always says not-authorized. Thanks for your help :-)
