### ISSUE TITLE
[solved] Compile error on Manjaro Linux - can not find the file: FreeImage.h in the directory

### ISSUE THREAD

**Issue by ds2k5** [davidgfnet/whatsapp-purple#402]
Hi,
using Manjaro Linux.

My steps:

0. Download source code, git clone https://github.com/davidgfnet/whatsapp-purple
1. compile, got error: fatal error: FreeImage.h: No such file or directory

can not find the file: FreeImage.h in the directory

What did i wrong ?
Thanks

Compiler: gcc (GCC) 5.3.0

here the log from compile
[compile.zip](https://github.com/davidgfnet/whatsapp-purple/files/195483/compile.zip)

**Comment by ds2k5** [comment]
sorry, found a solution:

sudo pacman -S freeimage

and there is a AUR too:  https://aur.archlinux.org/packages/purple-whatsapp/

**Comment by davidgfnet** [comment]
Yep Freeimage is a dependency. Searching for Freeimage in the issue list gets you an answer.
