### ISSUE TITLE
Some "How to" for build source code ????

### ISSUE THREAD

**Issue by inthemix84** [davidgfnet/whatsapp-purple#403]
Hello, there are some instructive to compile the source code ¨ and to indicate the dependencies that must tner installed ¨ Thanks

**Comment by Myppomeu** [comment]
For Debian 8:

> apt install protobuf-compiler libprotobuf-dev libfreeimage-dev libfreeimage3 libpurple-dev libpurple0
> git clone https://github.com/davidgfnet/whatsapp-purple
> cd ./whatsapp-purple
> make
> checkinstall

**Comment by inthemix84** [comment]
Excelent, building OK! in Ubuntu 15.10 x64

Thank
