### ISSUE TITLE
[Question] Is it possible to use whatsapp-purple while keeping my phone connected?

### ISSUE THREAD

**Issue by Phyks** [davidgfnet/whatsapp-purple#406]
Hi,

I cannot find this info in the doc, but is it possible to use whatsapp-purple to connect to whatsapp, while keeping my phone connected as well? I thought whatsapp enforced a one-device only policy, meaning that only one device could be connected to whatsapp (excepted if using whatsapp web).

At least, I had troubles with the cli clients, which were due to this and it was mentionned in the FAQ.

Thanks!

**Comment by hoehermann** [comment]
No. whatsapp-purple acts like a client on a phone. The limitation of one connected device is enforced by WhatsApp.

**Comment by Phyks** [comment]
Ok. Maybe adding this in the FAQ might be useful. Thanks for the answer!
