### ISSUE TITLE
Why isn't there a yowsup2Pidgin Bridge ?

### ISSUE THREAD

**Issue by wedok** [davidgfnet/whatsapp-purple#412]
Why not using yowsup in Pidgin instead of developing own stuff ?

**Comment by hoehermann** [comment]
Because yowsup is written in python. Wrapping a python module in a plugin to work with pidgin is a non-trivial task, either.

**Comment by assegaf** [comment]
yeah all is kinda annoying task, converting this to those, previously client app should be written in java as both Android and S40 is a java, which our app mimic to official app.

**Comment by wedok** [comment]
and why isnt there a python2pidgin bridge for yowsup ? :)
if people code vst2winamp and vice versa plugins are they supercoders ?
its a shame what pidgin and miranda peepz r doing. :(

**Comment by davidgfnet** [comment]
Hey that's a super nice idea! Thanks a lot! Never occurred to me!
I have another cool idea, why don't you do it? :D Looks like you've got plenty of free time as well!
Thanks mate!
