### ISSUE TITLE
Cambiar foto de perfil [Set profile picture?]

### ISSUE THREAD

**Issue by vk496** [davidgfnet/whatsapp-purple#51]
Se que es algo tonto (perdonen mi ignorancia), pero es posible cambiar la foto de perfil? Uso Pidgin en Linux

Gracias de antemano.

**Comment by davidgfnet** [comment]
Closing this as dup of #105. Please write in english, I don't care if you don't know english, as far as I know english is a compulsory subject in all spanish schools.
