### ISSUE TITLE
Group Chats

### ISSUE THREAD

**Issue by Bashar** [davidgfnet/whatsapp-purple#56]
After inviting the pidgin account to a group, when posting a message on the group from phone i get this error message, and no group chat is listed on my pidgin
![screenshot from 2013-10-13 23 02 53](https://f.cloud.github.com/assets/142219/1322678/9fa7bade-3442-11e3-8dc2-3e839c037302.png)

**Comment by giordano** [comment]
Just to make it easier to find this bug report using search engines, I copy here the content of the message:

> Invitation only
> Joining (null) requires an invitation.

I confirm restarting Pidgin helps to make the group chat appear.

Sorry for the noise.

**Comment by davidgfnet** [comment]
This is very old, I shall check this. Everybody recheck please, but I think we shouldn't have this problems any more.

**Comment by davidgfnet** [comment]
This should not be a problem any more!

**Comment by dektiram** [comment]
Invitation only
Joining (null) requires an invitation.

still happen in centos 7
