### ISSUE TITLE
Add Buddy Crash

### ISSUE THREAD

**Issue by peanutbutterandcheese** [davidgfnet/whatsapp-purple#57]
Whenever I try to add a WhatsApp buddy, Pidgin crashes. I get a message along the lines of "Lost connection with server. Connection reset by peer", before a segfault.
I'm using libpurple 2.10.7-4, pidgin 2.10.7-4 & purple-whatsapp-git v0.3.1.g28a91ce-1 on Arch Linux.
Replies to messages sent via yowsup are received successfully, aside from the same "Invitation Only" error as davidgfnet/whatsapp-purple/issues/56.

~~Here's some probably useless GDB output:~~
Edit: I recompiled with debugging so this snipped might be more useful:
https://gist.github.com/peanutbutterandcheese/b9d46046e07599193964
Also if I quickly add buddy as soon as I open the program it will succeed, but if I leave it  minute it will disconnect and crash. It disconnects even if I don't try to add a buddy so I have to keep hitting reconnect to get updates, perhaps a separate issue.

**Comment by davidgfnet** [comment]
This is way too old. Try new versions and create new issue if you can reproduce this again
