### ISSUE TITLE
Any Adium/OSX build plans?

### ISSUE THREAD

**Issue by braco** [davidgfnet/whatsapp-purple#67]

**Comment by Megachip** [comment]
@avarx looks like your repository isn't available anymore!?

**Comment by avarx** [comment]
@Megachip this is true. 
Since I didn't test&updated it for months I deleted it + I guess the API changed.

**Comment by ThYpHo0n** [comment]
Hi guys, I also stopped my maintainance work on the plugin, therefore I don't know if it's working at the moment.

**Comment by bra1nfuck** [comment]
We need it.
