### ISSUE TITLE
The server closed the connection

### ISSUE THREAD

**Issue by foxxx0** [davidgfnet/whatsapp-purple#73]
Hey, I'm trying to get Pidgin working with the whatsapp-purple library.

I"ve just registered a new account with a fresh number using yowsup and can login to that account to receive/send messages using yowsup too.

However I can't get it to work in pidgin.

System specs are:

System 1
OS: Windows XP SP3 (running in kvm/qemu + libvirtd VM)
Pidgin 2.10.7 (libpurple 2.10.7)
2013-12-01-whatsapp.dll

System 2
OS: Archlinux x64
Pidgin 2.10.7 (libpurple 2.10.7)
2013-12-23-whatsapp.so

On both systems I can't login into the account, the server closes the connection.

Pidgin Debug Output:

>(16:02:39) account: Connecting to account 49175xxxxxxx.
>(16:02:39) connection: Connecting. gc = 02683770
>(16:02:39) waprpl: logging in 49175xxxxxxx
>(16:02:39) dnsquery: Performing DNS lookup for c3.whatsapp.net
>(16:02:39) gtkutils: gdk_pixbuf_new_from_file() returned nothing for file C:\Programme\Pidgin\pixmaps\pidgin\protocols\16\whatsapp.png: Datei »C:\Programme\Pidgin\pixmaps\pidgin\protocols\16\whatsapp.png« konnte nicht geöffnet werden: No such file or directory
>(16:02:39) dnsquery: IP resolved for c3.whatsapp.net
>(16:02:39) proxy: Attempting connection to 173.193.247.212
>(16:02:39) proxy: Connecting to c3.whatsapp.net:443 with no proxy
>(16:02:39) proxy: Connection in progress
>(16:02:39) proxy: Connecting to c3.whatsapp.net:443.
>(16:02:39) proxy: Connected to c3.whatsapp.net:443.
>(16:02:41) connection: Connection error on 02683770 (reason: 0 description: Server closed the connection)
>(16:02:41) account: Disconnecting account 49175xxxxxxx (0263CC10)
>(16:02:41) connection: Disconnecting connection 02683770

Watching the netstat output on my system when logging in with yowsup I could see it connected to 50.22.231.40 but the default whatsapp-purple setting refers to c3.whatsapp.net which resolves to 173.193.247.208.
So I tried using the IP itself but it resulted in the exact same error.
I also noted, that c2.whatsapp.net (50.22.231.42) and c.whatsapp.net (50.22.231.44) are in same subnet as the server which is selected by using yowsup.

However I have no further ideas on how to get it working, please help.

Thanks in advance.

**Comment by pradeep0312** [comment]
hi i tried to register my number and get the code but it says " could not request registration code...the underlying connection was closed;could not establish trust relationship for the ssl/tls secure channel...
someone please help me...
its causing very trouble for me..

**Comment by davidgfnet** [comment]
To register a new number you cannot use whatsapp-purple, since it does not
ship this option.
Therefore I conclude you are using a 3rd party software. You are probably
asking on the wrong place.
Sorry

**Comment by pradeep0312** [comment]
i am using wart for registering

**Comment by thomaswpp** [comment]
i am using wart for registering, but, closed account, its not work whatsapp
https://github.com/shirioko/WART
