### ISSUE TITLE
2014-01-06-whatsapp.dll send but not receive any message

### ISSUE THREAD

**Issue by Jeronimo17** [davidgfnet/whatsapp-purple#85]
Pidgin is not messages show the people write you, this happens with friends and chat, but read messages on the server, because what you have left written is lost

**Comment by Plugue** [comment]
Hi,

First, David, Great job.

My application is not working properly. I configured the WhatsApp and message account are being sent but are not being received. Only texts are not being sent, the media are okay.

This problem again in version 0.8.5. Can you help me?
