### ISSUE TITLE
WhatsApp protocol doesn't appear in protocol list

### ISSUE THREAD

**Issue by d3bian83** [davidgfnet/whatsapp-purple#87]
Hi,

I've installed the plugin under Debian Wheezy 64bit with the following procedure, as superuser:

- installing Pidgin with apt-get
- downloading the file "last-whatsapp.so" from the address "http://davidgf.net/nightly/whatsapp-purple/x64/last-whatsapp.so" into /usr/lib/pidgin/
- renaming "last-whatsapp.so" to "whatsapp.so"

When I launch Pidgin (both as normal user and as root), WhatsApp doesn't appear in the protocol list when I try to create the new account.

Did I make any mistake in the procedure?
Thanks in advance

**Comment by davidgfnet** [comment]
Closing this...
