### ISSUE TITLE
Contact status is empty

### ISSUE THREAD

**Issue by davidgfnet** [davidgfnet/whatsapp-purple#88]
I have a bug on my whatsapp account. All contact statuses appear empty.
It seems to be an issue with the query for status returning an empty string.

This is happening with master at 8b10f2c14e
I checked with older versions and it seems to fail too. Probably something has changed in whatsapp protocol. Any idea?

**Comment by rigid** [comment]
i wonder what kind of spectrum issue this could be. The issue is still present in the latest spectrum/swift-2.x HEAD
