### ISSUE TITLE
Blocked account

### ISSUE THREAD

**Issue by nuraiman** [davidgfnet/whatsapp-purple#89]
Today I used for the first time the whatsapp-purple plugin. I was able to log in and chat.
It worked fine for 1 hour and then suddenly it log out with this message:

Server closed the connection

It tried with yousup and this is the output:
Detected cc: 39
status: fail
reason: blocked

I am using the latest version of the plugin + the latest version of pidgin on ubuntu 13.04.

What can i do?

**Comment by the98** [comment]
Hi, my account has also been blocked. What, exactly, should I e-mail whatsapp to get lucky? :P

**Comment by jack980517** [comment]
It seems that WhatsApp is now blocking any accounts that tried to use 3rd-party clients. I got blocked after using the password retrieval tool. Can you write here about how exactly you "lied" to them and help other people who encountered the same situation?
Also, I think a warning about this should be put on readme.md and/or the "user-friendly" instruction website...
